projects/laji/src/app/+taxonomy/species/service/taxon-export.service.ts

fix issue misapplied Names in excel download. Previously pickMisappliedNames method was picking erroneus data (scientific Name of basict taxon)

[#176168329] - fix issue misapplied Names in excel download

---

projects/laji/src/app/shared/navbar/navbar.component.html

In the English translation it makes more sense to
have it at the end.
I am mostly just doing this to test out and document
the process of making minor changes like this to see
if it works for non-developers.

Move more/teemat link to the end of the navbar

---

projects/laji/src/app/+project-form/form/named-place-linker/named-place-linker-button/named-place-linker-button.component.ts

Fixes for `named-place-linker-button`:
* Sending multiple doc requests
* Throwing error on doc find fail
* Don't fetch document if no need to (e.g. form doesn't use named places)

Clean named-place-linker-button observables [#176798676]

---

projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.ts
projects/laji/src/app/shared-modules/document-viewer/user-document-tools/user-document-tools.component.ts
projects/laji/src/app/shared/gallery/image-gallery/image-modal-overlay.component.ts
projects/laji/src/app/shared/gallery/image-gallery/image-modal.component.ts

shortcut didn't work well in annotation modal after open image modal. Same happens when user open images in taxon images tab.
Also component image-modal-overlay still have previous array of images when user move to annotation, so that generated some problem to shortcuts too

fix shortcut arrow keys in Annotation and Images modal

---

projects/laji/src/app/+project-form/form/document-form/document-form.component.ts
projects/laji/src/app/shared-modules/laji-form/document-form-header/document-form-header.component.ts

Makes the document form component clear the named place in laji-form-document facade, so that it won't have the previous named place in the state.
Fixes https://www.pivotaltracker.com/story/show/177181864

Document editor header clears named place

---

projects/laji/src/app/+user/profile/profile.component.ts
projects/laji/src/app/shared-modules/laji-form/laji-form/laji-form.component.ts
projects/laji/src/app/shared/service/user.service.ts

Currently the metadata settings default value doesn't work, because the defaults were locally in profile component only. I moved getting the profile to user service, so that it can be properly prepared there.

LajiForm receives the profile metadata setttings with default value [#177316308]

---

projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
projects/laji/src/app/+taxonomy/species/species-form/species-form.component.ts
projects/laji/src/app/shared-modules/search-filters/active/observation-active.component.ts

Testable at https://177772608.dev.laji.fi/en/taxon/list
Administrative status and Invasive species should be clearable now from the active filters list

Remove all option in taxon list is not effecting all filters [#177772608]

---

projects/laji/src/app/shared/gallery/image-gallery/image-modal.component.ts

In the document-annotation document, the image component didn't change the main picture. 
User move to next or previous by shortcuts, but when the observation is loaded, the main picture is always the same.
That happens when the next or the previous are from the same observation of the same user

fix issue on document annotation images - [#177723306]

---

projects/laji/e2e/src/+project-form/named-places.e2e-spec.ts
projects/laji/src/app/+project-form/form/named-place/np-edit-form/np-edit-form.component.ts
projects/laji/src/app/+project-form/project-form.service.ts

Steps to repro:
1. Make sure that you are admin of water bird form
2. Goto https://beta.laji.fi/project/MHL.65/form/MHL.65/places
2. Select some place
3. Click named place edit button of the selected place
4. Click cancel edit on the footer
Query contains filters for municipality, which can't be edited in the UI
Query doesn't contain filters that aren't editable in the UI

Fix filters after navigating from named place edit view [#178035225]

---

projects/laji-ui/src/lib/sidebar/sidebar.component.ts

1. Make your browser window narrower than ~700px
2. Goto https://beta.laji.fi/project/JX.652/about
3. Click "Send observations"
4. Click "Leave without saving"
5. Click "Send observations"
6. Try to click "Today" button on the form
-> The today button doesn't do anything
Fixed here: https://178157095.dev.laji.fi/project/JX.652
On mobile, the sidebar adds a click listener to the content of the sidebar, which prevents all click events (`onContentClick()`). The click listener is added in a timeout, and if `checkCloseOnClickListener()` is called sequantially multiple times before the timeout function executes, the click listener is added multiple times and the excess ones aren't cleaned properly, making the content unclickable.

Fix sidebar timeout bug [#178157095]

---

projects/laji/src/app/shared-modules/select/select/select.component.ts

Removes at least seeminly unnecessary d3 import from the select component, which causes a lint error about a shadowed variable later on. Should be merged ASAP so in the next cycle we won't have the lint errors that prevent commiting.

Rm unused import (fixes lint errors)

---

projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-result-filters/syke-insect-result-filters.component.ts

Route table for bumblebee census losing its observation counts is related to the origin year select bug, se branch build here https://311.dev.laji.fi/

Fix year select #2

---

projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.ts

Testable here: https://2997.dev.laji.fi/en/observation/list
Fixes the bug by removing annotationForm ViewChild that doesn't exist anymore (it can be seen in [this old version](https://bitbucket.org/luomus/laji.fi-front/src/5ce0de7b21de8c918aaa888cd69381f9925d0d2c/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.html) but has been since removed).

Fix clicking "select current" on annotation form shows error

---

projects/laji-ui/src/lib/tabs/tab/tab.component.ts
projects/laji-ui/src/lib/tabs/tabs.component.ts
projects/laji/src/app/+taxonomy/taxon/info-card/info-card.component.html
projects/laji/src/app/+taxonomy/taxon/info-card/info-card.component.ts
projects/laji/src/app/shared-modules/annotations/annotations.component.ts

The problem is in the taxon-card and it happens when i move between tabs and later i switch to another specie.
For example:
- go to taxon MX.44058
- move between tabs (at least open "occurrences" and "specimens")
- switch to other species by using dropdown menu in breadcrumbs. 
- if the next specie i open has less tabs than the previous, for example MX.44052, the content is not correct. 
2 components are opened at same time. At least i could see "specimens" and "occurrences" or "specimens" and "taxonomy" opened at same time.

fix bug in taxon card content tab when switch to other specie - 177659751

---

projects/laji/src/app/+project-form/form/named-place/np-edit-form/np-edit-form.component.ts

The new store has stricter validations, and thus a named place's `prepopulatedDocument` (of type `MY.document` in schema) with an empty object as the value is caught by the new stricter validators.
This PR makes it so that an empty `prepopulatedDocument` isn't added for all named places during creation/edit.
The fix is testable here (saving works, in beta it doesn't): http://178409200.dev.laji.fi/project/MHL.65/form/MHL.65/places/new
Task https://www.pivotaltracker.com/story/show/178409200

Don't initialize prepopulated document with empty [#178409200]

---

projects/laji/src/app/+project-form/form/named-place/named-place/named-place.component.ts

Don't know how to replicate this, but I found from the laji.fi error logs that quite often `npClick` is undefined or `infoView` is undefined. This patch makes calling the info component methods more robust.

Named place component is more careful when calling info view methods

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-overview.component.html
projects/laji/src/i18n/en.json
projects/laji/src/i18n/fi.json
projects/laji/src/i18n/sv.json

https://178466767.dev.laji.fi/en/taxon/MX.231366
https://www.pivotaltracker.com/story/show/178466767
This PR removes the download link under "Browse" section, since there isn't a download tab anymore on the observation page.

Remove taxon download link [#178466767]

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.ts

Instructions how to test this are on [the pivotal task](https://www.pivotaltracker.com/n/projects/2346653/stories/178461229/comments/224771619). 
Fixes SSR error caused by `element.getBoundingClientRect();` function being called on server.

Fix SSR error in taxon identification component

---

package-lock.json
package.json
projects/laji/src/app/+project-form/submissions/statistics/line-transect/line-transect-chart/line-transect-chart.component.ts
projects/laji/src/app/+project-form/submissions/statistics/line-transect/line-transect.component.ts

Fixes the line transect document stat charts:
* added typing
* remove bug that causes page to crash
* fix circle markers on the charts
Demo: https://178300485.dev.laji.fi/project/MHL.1/submissions/JX.130808
Repro on beta: https://beta.laji.fi/project/MHL.1/submissions/JX.130808

Line transect chart circles fix [#178300485]

---

projects/laji/src/app/shared-modules/laji-form/laji-form-document.facade.ts

Repro:
1. Goto https://beta.laji.fi/project/JX.519
2. Add a date & gathering with a geometry
3. Click date yesterday
4. Click submit very quickly right after step 3 (quicker than 3s)
5. After landing on Vihko home page, visit any other page (e.g. observations), navigate back to Vihko home page and you'll see the duplicate
This happens because:
1. At repro step 3 the `dataSub` is triggered, and it will wait 3s before continuing it's course
2. At repro step 4 the document is saved and the tmp doc is removed
3. After the 3s delay the `dataSub` saves the tmp item again.
The 3s delay has probably acted as a debouncer, so this could add a slight penalty to the form responsiveness. The form component itself has already a debouncer for string inputs, so I don't think it should be a big problem.

laji-form facade doesn't use timeout when reacting to data change [#178498572]

---

projects/laji/src/app/shared-modules/own-submissions/own-datatable/own-datatable.component.html

Got detail row to show its full contents and made the arrows indicating detail row to change correctly. Example at https://178535861.dev.laji.fi/project/MHL.1/form/MHL.1/places?activeNP=MNP.27385

Named place viewer document list on smaller-than-half-screen width

---

projects/laji/src/app/shared-modules/laji-form/laji-form-document.facade.ts

Affects both prepopulated & accepted document.
Steps to reproduce:
1. Goto https://beta.laji.fi/project/MHL.1/form/MHL.1/places?activeNP=MNP.27408
2. Reserve the place to yourself
3. Compare https://beta.laji.fi/project/MHL.1/form/MHL.1/places/MNP.27408 and https://178540041.dev.laji.fi/project/MHL.1/form/MHL.1/places/MNP.27408 (beta shows Ville-Matti Riihikoski and you as observer, task demo site doesn't).

Don't populate leg into empty document when using named place [#178540041]

---

projects/laji/src/app/shared-modules/observation-result/selected-field-group/selected-field-group.component.ts
projects/laji/src/app/shared-modules/observation-result/selected-field-item/selected-field-item.component.ts

When selecting columns to show in observation table. if the order of columns is changed with arrow buttons now columns jump over all columns belonging to a multicolumn field, and don't split them as before. Branch build in https://178281906.dev.laji.fi/

Sorting multi columns results in incorrect order 178281906

---

projects/laji/src/app/+observation/form/observation-form.component.html
projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
projects/laji/src/app/shared/api/WarehouseApi.ts

Added a new method to warehouseApi to call filters-endpoint, changed metadata-select-component to use it when requested, currently used only for lifestage, but should be easily usable for any filter present in the endpoint.

Lifestage filter missing values

---

projects/laji/e2e/helper.ts
projects/laji/e2e/src/+project-form/project-form.e2e-spec.ts
projects/laji/e2e/src/+project-form/project-form.po.ts
projects/laji/e2e/src/+vihko/home.po.ts
projects/laji/e2e/src/shared/nav.po.ts
projects/laji/src/app/+haseka/haseka.component.html
projects/laji/src/app/+project-form/form/document-form/document-form.component.ts
projects/laji/src/app/+project-form/form/form.component.ts
projects/laji/src/app/+project-form/guards/abstract-permission-guard.ts
projects/laji/src/app/shared-modules/laji-form/document-form/document-form.component.ts

https://www.pivotaltracker.com/story/show/178616856
Bug repro:
1. Go to English trip form https://laji.fi/en/vihko/home
2. Click Leave without saving
**What's the expected result?**
I'm on English page at https://laji.fi/en/vihko/home
**What's the actual result?**
I'm on Finnish page at https://laji.fi/vihko/home
Fixed all other navigation inside project form code also to translate the routes properly.

Project forms respect the selected lang when navigating [#178616856]

---

projects/laji/src/app/shared-modules/document-viewer/images/images.component.ts

https://www.pivotaltracker.com/story/show/178627685
Annotation page currently shows all gathering photos, not only highlighted.
https://178627685.dev.laji.fi/view?uri=http:%2F%2Ftun.fi%2FJX.267488&highlight=http:%2F%2Ftun.fi%2FJX.267488%237&own=true&openAnnotation=true

Fix annotation page showing incorrect photos

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-taxonomy/taxon-taxonomy.component.html

Fixed taxonomy source links leading to laji.fi front page instead of the correct place. Branch build and example card: https://179433569.dev.laji.fi/taxon/MX.26277/taxonomy

Fixed nonworking taxon source link.

---

projects/laji/src/app/+viewer/viewer-print/viewer-print.component.css
projects/laji/src/app/+viewer/viewer-print/viewer-print.component.html

https://www.pivotaltracker.com/story/show/179218468
https://179218468.dev.laji.fi/view/print?uri=http:%2F%2Ftun.fi%2FJX.276210&own=false&showFacts=false
Remove print pdf button because pdf generation has problems (map sometimes behaves weirdly, images don't load)

Remove viewer print pdf button 

---

projects/laji/src/app/+project-form/form/document-form/document-form.component.ts
projects/laji/src/app/shared-modules/laji-form/document-form-footer/document-form-footer.component.html
projects/laji/src/app/shared-modules/laji-form/document-form-footer/document-form-footer.component.ts
projects/laji/src/app/shared-modules/laji-form/document-form/document-form.component.html
projects/laji/src/app/shared-modules/laji-form/document-form/document-form.component.ts

The `cancel` is a reserved event, and on Firefox it is called for the `document-form` component when laji-form file dialog is cancelled. On chrome the bug doesn't exist.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDialogElement/cancel_event
Repro steps @ https://www.pivotaltracker.com/story/show/179412522

Rename document form cancel event with leave

---

projects/laji/e2e/src/+theme/datasets/datasets.e2e-spec.ts
projects/laji/e2e/src/+theme/datasets/datasets.po.ts
projects/laji/src/app/+theme/datasets/datasets.component.html
projects/laji/src/app/+theme/datasets/datasets.component.ts
projects/laji/src/app/shared/service/form-permission.service.ts
projects/laji/src/environments/global.ts

Currently the list of the data bank forms is the `$.options.forms` list of form `MHL.67`. This causes a bug that when navigating to edit a document of some databank form that is on that list, the URL get malformed as the project-form code interprets the data bank form being a sub form, which it isn't in this context.
To fix this, the list of the data bank forms should be derived from filtering all the forms with the `$.options.databank` option. The form with list of the data bank forms (`MHL.67`) should be removed after this.

Remove databank owners form [#179685221]

---

projects/laji/src/app/+project-form/form/named-place/np-edit-form/np-edit-form.component.ts

Editing a named place now wraps the named place's geometry inside a GeometryCollection -> inconsistent data. Fixes probably multiple bugs, at least found this old pivotal ask:
https://www.pivotaltracker.com/story/show/178391265
Also after editing e.g. winter bird routes, the route list doesn't display the YKJ coordinates for the route because it's trying to show `geometry.coordinateVerbatim`, and the path is now `geometry.geometries[0].coordinateVerbatim` (after a second edit it'd be geometry.geometries[0].geometries[0].coordinateVerbatim`) 
Demo: https://178391265.dev.laji.fi/project/MHL.3

Named place edit form doesn't wrap geometry to GeometryCollection [#178391265]

---

projects/laji/src/app/+project-form/results/wbc-result/wbc-species-charts/wbc-species-linecharts/wbc-species-linecharts.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-group-select.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-group-select.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list-breadcrumb/informal-list-breadcrumb.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list-breadcrumb/informal-list-breadcrumb.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list/informal-list.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list/informal-list.component.ts
projects/laji/src/app/shared/navbar/notifications/notifications.facade.ts
tsconfig.json

Enables the strictBindCallApply tsc option (one of the options included in strict mode) and fixes all related errors.
There were also some confusing names and stuff in `informal-group-select` that I refactored as byproduct.

Enable strict bind call apply 180206625

---

projects/laji/src/app/+project-form/form/document-form/document-form.facade.ts
projects/laji/src/app/+project-form/form/named-place-linker/named-place-linker-button/named-place-linker-button.component.ts
projects/laji/src/app/+project-form/form/named-place-linker/named-place-linker.component.ts
projects/laji/src/app/shared-modules/own-submissions/service/document.service.ts

Repro:
1. Goto https://180292736.dev.laji.fi/vihko/ownSubmissions
2. Open network tab to see the requests made
3. Open some of your trip report documents
- /document data is fetched one time
- /document data is fetched two time
I fixed this by adding a `findById` method with a cache to the document service, which the document form facade and the named place linker both use, so that the request is done only once.

Document request done only once on document form page [#180292736]

---

projects/laji/src/app/+project-form/project-form.component.html
projects/laji/src/app/shared-modules/latest-documents/latest/haseka-users-latest.component.ts
projects/laji/src/app/shared-modules/latest-documents/latest/short-document.component.html
projects/laji/src/app/shared-modules/latest-documents/latest/short-document.component.ts
projects/laji/src/app/shared-modules/own-submissions/own-submissions.component.ts
projects/laji/src/app/shared/service/document-info.service.ts

Pivotal task https://www.pivotaltracker.com/story/show/180292750
Demo: https://180292750.dev.laji.fi/vihko/home
Currently the short docs (=document viewers in the sidebar on e.g. `/vihko/home`) made a named place request if the document had a named place ID. This made the page increasingly unresponsive. With this PR, the short doc doesn't do any requests.
I also fixed a bug that made the short doc never display the form name. The problem was that even though `showFormName` was `true` by default, the short doc is always wrapped inside a `haseka-user-latest` which didn't have a default value, making the value `undefined`. Short docs under project forms don't display the form name, as it's already implicit.

Short doc no named place requests [#180292750]

---

projects/laji/e2e/src/+project-form/project-form.e2e-spec.ts
projects/laji/e2e/src/+project-form/project-form.po.ts
projects/laji/src/app/shared-modules/own-submissions/own-datatable/own-datatable.component.html
projects/laji/src/app/shared/service/history.service.ts

Fixes the following bug: https://www.pivotaltracker.com/story/show/180291183
Demo https://180291183.dev.laji.fi/project/MHL.45/submissions
The issue was that the history service pushed navigations with `replaceUrl: true` to the history stack. [The docs state that it shouldn't push to the history](https://angular.io/api/router/NavigationBehaviorOptions#skipLocationChange). I took the technique for checking the `replaceUrl` in the history service from this [angular PR comment](https://github.com/angular/angular/pull/22739#issuecomment-647773274)
The only other place where `replaceUrl` is used is the taxon pages. I tested the back navigation on the taxon pages manually and it works ok.

history service filters route with replaceUrl [#180291183]

---

projects/laji/src/app/+news/news.component.ts

If a news item has no featuredImage, parses through the html to find the first image of the article and uses that in meta tags. The meta tags should only be necessary on the server.

Parse default meta img from news content

---

projects/laji/src/app/+project-form/form/named-place/np-edit-form/np-edit-form.component.ts

https://www.pivotaltracker.com/story/show/180290817
https://180290817.dev.laji.fi/project/MHL.45 (or any other form with named places editing enabled)
Not related to release 49 btw, so no need to include in that release
1. go edit some named place
2. make some changes
3. click "leave without saving"
4. click "cancel"
You are redirected back to where you came from, so the confirmation dialog is pointless.
Canceling closes confirmation dialog and doesn't redirect user

Fix named place edit leave confirmation [#180290817]

---

projects/laji/src/app/+map/front/front.component.html
projects/laji/src/app/+map/front/front.component.ts
projects/laji/src/app/shared-modules/laji-map/laji-map.interface.ts

Demo https://180434670.dev.laji.fi/map?layers=cgrsGrid,afeGrid,openStreetMap&world=true 
Task https://www.pivotaltracker.com/story/show/180434670
* Adds the possibility to preselect any layers via `layers` query param in the URI
* Adds the possibility to start map with world projection with the `world` query param in the URI
* Don't render observation map if there are extra params

Map tilelayers param [#180434670]

---

projects/laji/src/app/+observation/form/observation-form.component.html
projects/laji/src/app/+observation/form/observation-form.component.ts
projects/laji/src/app/+observation/form/own-observations-filter/own-observations-filter.component.html
projects/laji/src/app/+observation/form/own-observations-filter/own-observations-filter.component.ts
projects/laji/src/app/+observation/observation-component.module.ts
projects/laji/src/app/+observation/search-query.service.ts

https://www.pivotaltracker.com/story/show/180269525
Extracted a component from observation-form and refactored the logic as well as fixed the "cannot deselect" bug.
About the `ownFilterChangeLookup`... I think a state lookup table like this is much easier to read than some `if` spaghetti (like we used to have and I really struggled to comprehend), even if there's some redundancy.

Own obs form refactor ("Cannot deselect"-task)

---

projects/laji/src/app/shared-modules/observation-result/observation-year-chart/observation-year-chart.component.ts

"Observations per year" chart shows also years that don't have data.
Task:
https://www.pivotaltracker.com/story/show/180570592
Testable here:
https://180570592.dev.laji.fi/en/observation/statistics?informalTaxonGroupId=MVL.582

Observation year chart doesn't skip years that don't have data

---

projects/laji/src/app/+project-form/about/about.component.html
projects/laji/src/app/+project-form/project-form.component.html
projects/laji/src/app/shared-modules/latest-documents/latest-documents.facade.ts
projects/laji/src/app/shared-modules/latest-documents/latest/haseka-users-latest.component.ts
projects/laji/src/app/shared-modules/own-submissions/own-submissions.component.ts
projects/laji/src/app/shared/api/DocumentApi.ts

Task: https://www.pivotaltracker.com/story/show/180618581
Demo: https://180618581.dev.laji.fi/project/MHL.51
The project form page is supposed the latest docs in the sidebar (or if the form is a mobile form, on the about page). It worked ok for local tmp docs, but the remote docs showed only the form's docs if they happened to be very recent (in the 10 docs you have last reported). The fix was to pass the formID to the query being made.

Project form latest docs fix [#180618581]

---

projects/laji/src/app/+project-form/form/document-form/document-form.facade.ts

Task https://www.pivotaltracker.com/story/show/180717623
Bug demo: https://beta.laji.fi/project/JX.519/form/JX.283171
Fix demo https://180717623.dev.laji.fi/project/JX.519/form/JX.283171
The named place pipe crashes silently on a null pointer error, resulting in wrong error message being displayed.

Fix document form facade named place observable [#180717623]

---

projects/laji/src/app/+project-form/form/document-form/document-form.facade.ts
projects/laji/src/app/+project-form/submissions/statistics/common/accepted-document-approval/accepted-document-approval.component.ts
projects/laji/src/app/shared-modules/own-submissions/service/document.service.ts

Pivotal task: https://www.pivotaltracker.com/story/show/180748974
Testable here: https://180748974.dev.laji.fi/vihko/templates
Fixes a bug where prefilled forms can only be used once without logging out or refreshing the page. The problem was that the `documentService.removeMeta` function modifies the document object directly so we need to make a copy of it before calling it.

Fix prefilled forms can be only used once

---

projects/laji/src/app/shared/service/taxon-autocomplete.service.ts

Task https://www.pivotaltracker.com/story/show/180807563
Demo https://180807563.dev.laji.fi/
This PR improves the omni search bolding search word matches by following ways:
1. Fixes bug when searching "rosa b" (`<b>` tags messed up in results)
2. Tokenizes the search words, so that search for "ly ly" bolds both words from the result "**Ly**rella **ly**ra"
3. Bolds start or end of word (e.g. search for "rosa a" bolds as "**Rosa a**lba" and "**Rosa** bland**a**")

Omnisearch bold bug [#180807563]

---

projects/laji/src/app/shared-modules/latest-documents/latest-documents.facade.ts
projects/laji/src/app/shared-modules/latest-documents/latest/haseka-users-latest.component.ts

Task: https://www.pivotaltracker.com/story/show/180846101
Demo: https://180846101.dev.laji.fi/project/MHL.3/form
The bug being fixed here is after submitting a new document for a project form, the latest docs in the sidebar will show all documents instead of just that form's documents. I added a `setFormID()` method to the latest docs facade, so that the `update()` method can be called without resetting the formID (previously the `update()` method updated the formID for the facade).

Latest docs bug on project form [#180846101]

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-children-data-source.ts
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.ts
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.facade.ts

- Refactored sub-mainrank finding logic (the closest main rank that is below the rank of the taxon)
- Fixed behavior when taxon rank is below the lowest mainrank
- Fixed old data source being potentially disconnected more than once
- Made sure the loader disappears after the sub-mainrank has been received regardless of if there are any child species
https://www.pivotaltracker.com/story/show/180717763
https://180717763.dev.laji.fi/taxon/MX.5073946/identification

Taxon identification fix 180717763

---

projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.component.ts
projects/laji/src/app/shared-modules/tree-select/tree-select-modal/tree-select-modal.component.ts

https://www.pivotaltracker.com/story/show/181170753
Not entirely sure if there could be more bugs related to this (the issue seems to stem from that `includedOptions` and the `treeModel` ids are out of sync?), but at least the null pointer is fixed.

Fix null pointer for tree select modal [#181170753]

---

projects/laji/src/app/+observation/form/observation-form.component.ts

Fixes this bug: https://www.pivotaltracker.com/story/show/182206341
The problem was that the `observation-form` taxon pill list changes were handled with `updateSearchQuery()` method, which is used by many other parts of the component to update the search query. The bug surfaced only now because `updateSearchQuery()` has before the polygon search feature received only `string` values (now it receives a `number` from the coordinates intersection buttons, and the `value.indexOf` check fails.

Fix observation-form taxon list changes are handled in separate method [#182206341]

---

projects/laji/src/app/+project-form/form/document-form/document-form.facade.ts

Document form failed for documents that had so many annotations that they resulted in multiple paged requests. I added the page to the annotation cache key, so it works.
This is hard to debug, but I think the error is so obvious that a simple code review is enough. I tested that it works.

Fix document-form annotation cache

---

package-lock.json
package.json
projects/laji/e2e/protractor.conf.js

Easy way to catch more bugs. I excluded some 3rd party issues, and removed the `onComplete` hook from protractor config since it caused the `protractor-console-plugin` not to work and I don't see why the hook would be necessary.

Protractor tests fail on console errors

---

projects/laji/src/app/+taxonomy/taxon/info-card/info-card-header/info-card-header.component.html

Allowed the breadcrumb rendering html to show items in taxon rank, task: https://www.pivotaltracker.com/story/show/182260001, branch: https://182260001.dev.laji.fi/taxon/MX.214519/occurrence

Show species rank on breadcumb

---

projects/laji/src/app/shared-modules/datatable/service/datatable-util.service.ts

Hopefully changes all datatable download array-type columns separators to semicolon, task: https://www.pivotaltracker.com/story/show/182010275, branch: https://182010275.dev.laji.fi/taxon/list

Use semicolon as field separator inside light download file cells

---

projects/laji/src/app/shared-modules/datatable/datatable-templates/datatable-templates.component.html

Fixed three datatable templates which would manifest the same bug. Task: https://www.pivotaltracker.com/story/show/181544383, branch: https://181544383.dev.laji.fi/observation/list.

HTML-bug showing species name em-dash incorrectly in hovertext

---

projects/laji/src/app/+observation/form/conservation-filter/conservation-filter.component.html

Currently can't change the filter section header "Administrative status"
in Crowdin. This fix should make that possible.

Make filter subtitle localizable

---

projects/laji/src/app/shared/navbar/navbar.component.ts
projects/laji/src/app/shared/navbar/notifications/notifications.facade.ts

https://www.pivotaltracker.com/story/show/180080394
Fixes (most instances of) double notification queries and changes the time interval to 5min. From pivotal:
>Updating unseen notifications is done through regular graphql queries (now at 5 minute intervals), but once the notifications dropdown is opened the list (which uses virtual scrolling) uses the regular api.

Notification queries 180080394

---

projects/laji/src/app/shared-modules/spreadsheet/importer/erroneous-first.pipe.ts
projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.html
projects/laji/src/app/shared-modules/spreadsheet/service/import.service.ts
projects/laji/src/app/shared-modules/spreadsheet/service/mapping.service.ts
projects/laji/src/app/shared-modules/spreadsheet/spreadsheet.module.ts

https://www.pivotaltracker.com/story/show/182750980
https://www.pivotaltracker.com/story/show/183101256
Fixes Vihko import failing silently with data that is missing document/gathering/unit level data. This pull request also changes the order of rows in the summary table so that the erroneous rows are shown first.

Vihko import fix

---

projects/laji/src/app/+project-form/form/laji-form/laji-form/laji-form.component.ts

https://www.pivotaltracker.com/story/show/183626555
https://183626555.dev.laji.fi/project/JX.519/form
LajiForm notifications weren't handled inside Angular Zone, so Angular couldn't properly handle them in it's internal event handling, or "zone" if you will.

Handle laji-form notifications inside ngZone

---

projects/laji/src/app/shared-modules/dataset-metadata/dataset-metadata-browser/dataset-metadata-browser.component.ts

If page is loaded with an empty collection selected the tree switches to showing empty collections and selects it from the hierarchy, opening the tree to its level. Testable branch https://183624947.dev.laji.fi/theme/dataset-metadata/.

Always show selected dataset in hierarchy 183624947

---

projects/laji/e2e/src/+observation/observation.e2e-spec.ts
projects/laji/e2e/src/+observation/observation.po.ts
projects/laji/src/app/+observation/form-sample/form-sample.component.html
projects/laji/src/app/+observation/form/date-form/date-form.component.html
projects/laji/src/app/+observation/form/date-form/date-form.component.ts
projects/laji/src/app/+observation/form/observation-form.component.html
projects/laji/src/app/+observation/form/observation-form.component.ts
projects/laji/src/app/+observation/view/observation-view.component.html
projects/laji/src/app/+observation/view/observation-view.component.ts
projects/laji/src/app/+theme/quality/quality-filters/quality-filters.component.html
projects/laji/src/app/shared-modules/own-submissions/own-datatable/own-datatable.component.html
projects/laji/src/app/shared/datepicker/datepicker.component.css
projects/laji/src/app/shared/datepicker/datepicker.component.html
projects/laji/src/app/shared/datepicker/datepicker.component.ts
projects/laji/src/app/shared/panel/panel.component.html

Fixes https://www.pivotaltracker.com/story/show/183827818
Demo https://183827818.dev.laji.fi/observation/list
* removes all input variables from the datepicker that aren't either used, or have always the same value in every instance where the component is used
* I'd like to note that we shouldn't have input variables "just in case" - that adds complexity without necessarily adding any value
* date format for the actual value is strictly always `ISO-8601`
* date view format is always in Finnish format (e.g. "1.2.2022")
* handle the state with minimal amount of variables:
* actual value is a simple `string` - could've been a `Moment` value but I prefer simple `string`s since they can be guaranteed to be immutable
* the calendar UI value is a `Moment` instance because it needs more …

Refactor laji-datepicker [#183827818]

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.html
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.scss
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.ts
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.html
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.scss
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.ts
projects/laji/src/app/shared/gallery/image-gallery/image-modal-overlay.component.html

This pull request contains two stories.
---
https://183720157.dev.laji.fi/taxon/MX.39248/identification
https://www.pivotaltracker.com/n/projects/2346653/stories/183720157
Clicking any image (except for the no-image icon) opens the image into a modal. Also, refactored the image copyright rendering into the same component with the image rendering.
---
https://183720157.dev.laji.fi/taxon/MX.204722/images
https://www.pivotaltracker.com/n/projects/2346653/stories/183749970
The image modal displays all captions. Previously it only has shown "caption" field content, now it also shows "taxonDescriptionCaption" field content.

Identify-tab image viewer [#183720157]

---

projects/laji/src/app/+observation/form/observation-form.component.html

https://183899007.dev.laji.fi/en/observation/list
https://www.pivotaltracker.com/n/projects/2346653/stories/183899007
Fixes 2022. "Scientific collections -> Collection" -filter was no longer needed in observation search, so it is removed in this pull request.

Collection filter removed from the observation search [#183899007]

---

projects/laji-ui/src/lib/button/button.component.html
projects/laji-ui/src/lib/button/button.component.ts
projects/laji/src/app/shared/directive/ssr-disable.directive.ts

https://www.pivotaltracker.com/story/show/183838261
If the user filled the GIS download form before the page had fully loaded, it reset. This was fixed by disabling radio buttons and lu-buttons when server side rendering.

Fix GIS download selection resetting

---

projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts

https://23456.dev.laji.fi/
* coordinate query geometries are now "below" other geometries so they don't stop click events
* finnish map now displays coordinate query geometries
Known issues:
* everything inside every geometry forces `cursor: pointer` (laji-map/leaflet issue)

display coordinate query geometry in finnish mode

---

projects/laji/src/app/+observation/form/date-form/date-form.component.html
projects/laji/src/app/+observation/form/date-form/date-form.component.ts
projects/laji/src/app/shared/datepicker/datepicker.component.ts

https://www.pivotaltracker.com/story/show/184323833
https://184323833.dev.laji.fi/observation/statistics?countryId=ML.206&qualityIssues=BOTH&firstLoadedSameOrAfter=2023-01-20&observerPersonToken=true
The laji-datepicker was used with two-way binded ng model (`[(banana in a box syntax)]`), and it also had a change event listener. That didn't make sense, so it made it use only the two-way binded ng model. It had broken after the datepicker refactoring which made the datepicker implement ngModel value accessor interface better.

fix obs search filters date change management [fixes #184323833]

---

projects/laji/src/app/+home/home.component.html
projects/laji/src/app/+home/home.components.ts
projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts

https://www.pivotaltracker.com/story/show/184370599
https://184370599.dev.laji.fi
The obs map on the front page redirects to /observation/map on click. The map view is also locked (can't be panned/zoomed).

Fix front page obs map [#184370599]

---

projects/laji/src/app/shared/service/taxon-autocomplete.service.ts

https://www.pivotaltracker.com/story/show/184370436
https://184370436.dev.laji.fi/observation/list
Escape regexp on omnisearch when adding bolding.

Fix omnisearch with parenthesis [#184370436]

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-biology/taxon-biology.component.html
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-biology/taxon-biology.component.ts
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-overview.component.ts
projects/laji/src/app/+taxonomy/taxon/service/check-lang.service.ts

https://184388410.dev.laji.fi/taxon/MX.205601/biology
https://www.pivotaltracker.com/n/projects/2346653/stories/184388410
In some cases, some descriptions were not rendered on taxon card's biology tab. Turned out that the reason was a condition that prevented showing the whole description group if any number of its variables were not translated into the used language (line 32 of taxon-biology-component.html). Now the condition for showing the group passes, if at least one variable has translations in the used language. Each variable has their own check now, and is shown if there's content in the used language.
On top that, this PR includes a refactor of CheckLangService, which seemed to have a lot of unused variables and functionalities, so I deleted those and renamed variables and …

Fix biology tab descriptions & Refactor CheckLangService [#184388410]

---

projects/vir/src/app/+home/home.component.html
projects/vir/src/app/+home/home.module.ts

https://183451212.viranomaiset-dev.laji.fi/
https://www.pivotaltracker.com/n/projects/2346653/stories/183451212
PAP home page did not show alert of technical news, this is fixed now. Probably hard to test with the feature branch page, but there's a screenshot in Pivotal Tracker.

Technical news alert to PAP home page [#183451212]

---

projects/laji/src/app/graph-ql/service/base-data.service.ts
projects/laji/src/app/shared/service/triplestore-label.service.ts

https://www.pivotaltracker.com/story/show/184256724
https://184256724.dev.laji.fi/en/taxon/list?onlyFinnish=true
Species list download used to get stuck easily because it executed a function called `dataToLookup` way too many times. I moved the function to `base-data.service` and added caching.

Fix species download getting stuck

---

projects/laji/src/app/shared-modules/spreadsheet/importer/col-mapper/col-mapper.component.ts
projects/laji/src/app/shared-modules/spreadsheet/model/excel.ts

https://www.pivotaltracker.com/story/show/184274259
https://184274259.dev.laji.fi/theme/datasets
This fixes data importer complaining about required columns when user tries to delete data. Now it doesn't check the required columns if there is a "delete" column in the file.

Fix data bank delete

---

projects/laji/src/app/shared/directive/ssr-disable.directive.ts

https://www.pivotaltracker.com/story/show/184205197
This can only be tested in beta or with local SSR (and the throttling needs to be on to see it). I changed the SSR disable directive to disable all inputs and not just those with certain types. If the user changes an input value when the page is not fully loaded, it will reset when the page finishes loading so it's better to disable the inputs before that.

Disable all inputs when server side rendering

---

projects/laji/src/app/shared-modules/collections-select/collections-select.component.html
projects/laji/src/app/shared-modules/collections-select/collections-select.component.ts
projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.component.html
projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.component.ts
projects/laji/src/app/shared-modules/tree-select/tree-select-modal/tree-select-modal.component.ts
projects/laji/src/app/shared-modules/tree-select/tree-select.component.html
projects/laji/src/app/shared-modules/tree-select/tree-select.component.ts

https://184003345.dev.laji.fi/observation/statistics
https://www.pivotaltracker.com/story/show/184003345
The reason for this bug was that the `collections$` observable (in`projects/laji/src/app/shared-modules/collections-select/collections-select.component.ts`) was recreated when the query changed and the tree select component subscribed only the first observable. It's preferred that the observables are created only once so I changed that for both collection select and informal group select. I also added some caching.

Fix collection filter 184003345

---

projects/laji/src/app/shared-modules/collections-select/collections-select.component.html
projects/laji/src/app/shared-modules/collections-select/collections-select.component.ts
projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.component.html
projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.component.ts
projects/laji/src/app/shared-modules/tree-select/tree-select.component.html
projects/laji/src/app/shared-modules/tree-select/tree-select.component.ts
projects/laji/src/app/shared-modules/tree-select/tree-selector/tree-selector.component.ts

https://184459097.dev.laji.fi/project/MHL.3/submissions
https://www.pivotaltracker.com/story/show/184001583
Fixes two bugs in tree select (informal group + collection select)
- selecting informal group before the component has loaded initial selection caused an error
- clear button didn't work

Tree select fixes

---

projects/laji/src/app/+project-form/form/document-form/document-form.component.html
projects/laji/src/app/+project-form/form/form.module.ts

https://184379680.dev.laji.fi/project/MHL.45
https://www.pivotaltracker.com/story/show/184379680
Removes the document table from document form.
The difference to dev can be seen by navigating to some lolife document that has prior observations.

Rm doc table from doc form [#184379680]

---

projects/laji/src/app/shared-modules/tree-select/tree-select.component.ts
projects/laji/src/styles/laji.scss

https://183943758.dev.laji.fi/observation/list
https://www.pivotaltracker.com/story/show/183943758
Scrollable modal style didn't work for all modals (see example in the pivotal task) so I removed it from the default styles and added a class `scrollable-modal`

Remove scrollable modal style from default styles

---

projects/laji-ui/src/lib/sidebar/sidebar.component.scss
projects/laji/src/app/+observation/view/observation-view.component.ts
projects/laji/src/app/+taxonomy/taxon/taxon.component.scss
projects/laji/src/app/shared/service/toasts.service.ts
projects/laji/src/i18n/fi.json

https://184017766.dev.laji.fi/observation
The page shows an info toast about the new search button after the user touches the observation filters.
This also fixes the style of the sidebar in the species card (https://dev.laji.fi/taxon/MX.46587?showTree=true) that was broken by the observation search pull request.

Observation search alert

---

projects/laji/src/app/+observation/observation.facade.ts
projects/laji/src/app/+observation/view/observation-view.component.ts
projects/laji/src/i18n/fi.json

https://184017766.dev.laji.fi/observation
Changes the observation search info toast so that it is shown only once. I did that by bringing back the `persistentState` to `ObservationFacade`. This pull request also removes the coordinate info toast that was not needed anymore.

Observation search alert fine-tuning

---

projects/laji/src/app/+observation/result-front/observation-result-front.component.html
projects/laji/src/app/shared-modules/info-page/info-page-loading.component.ts
projects/laji/src/app/shared-modules/info-page/info-page.component.ts
projects/laji/src/app/shared-modules/info-page/info-page.module.ts
projects/laji/src/app/shared/directive/if-width-above-breakpoint.directive.ts

Since this is related to the server side rendering, it can only be tested with local ssr or after it has been merged. Observation front page (https://laji.fi/observation) looks weird while it is loading because the server can't know the screen width and it always shows the mobile view first. I changed it so that is shows a loading component on the server side.

Observation front page fine-tuning

---

projects/laji/src/app/shared-modules/select/select-subcategories/select-subcategories.component.ts

Story: https://www.pivotaltracker.com/story/show/184654630, testable here https://184654630.dev.laji.fi/observation/list?collectionAndRecordQuality=PROFESSIONAL:EXPERT_VERIFIED,COMMUNITY_VERIFIED,NEUTRAL,UNCERTAIN;HOBBYIST:EXPERT_VERIFIED,COMMUNITY_VERIFIED,NEUTRAL;AMATEUR:EXPERT_VERIFIED,COMMUNITY_VERIFIED, problem was that for laji.fi to set the filters properly that last COMMUNITY_VERIFIED needed to be followed by a semicolon, now it works with or without it.

CollectionAndRecordquality filter values not properly set 184654630

---

projects/laji/src/app/shared-modules/document-viewer/service/document-permission.service.ts
projects/laji/src/app/shared/service/form-permission.service.ts

https://185177956.dev.laji.fi
https://www.pivotaltracker.com/n/projects/2346653
Previously the document permission service used both form ID and collection ID to determine if the user is a form admin but all the documents don't have a form ID and the form check is unnecessary so now it uses only the collection ID.

Document permission service change

---

projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-result.service.ts

TAsk here https://www.pivotaltracker.com/story/show/184626236, problem was that in the tables scientific name was used to identify taxons, which informal taxon groups do not have, so they were identified as undefined and in the table latter informal groups would just overwrite earlier ones. using taxon id now as identifier.

Fix taxa shown on bumblebee census results #184626236

---

projects/laji/src/app/+information/information.component.html
projects/laji/src/app/+information/information.module.ts
projects/laji/src/app/+taxonomy/browse-species/browse-species.component.html
projects/laji/src/app/+taxonomy/species/species.component.html
projects/laji/src/app/+taxonomy/taxon/taxon.component.html

Task here https://www.pivotaltracker.com/story/show/185049817, probably not on all pages, but then news should now show up on all taxon pages and cms-pages.

Add technical news to all pages #185049817

---

projects/laji/src/app/+observation/download/observation-download.component.html

Task here https://www.pivotaltracker.com/story/show/184335236, the element for lightweight download is now kept hidden until the number of observations has been retreived from api.

Bypassing download size limit #184335236

---

projects/laji/src/app/shared-modules/document-viewer/viewer-map/viewer-map.component.html
projects/laji/src/app/shared-modules/document-viewer/viewer-map/viewer-map.component.ts

Task here https://www.pivotaltracker.com/story/show/185412397, there were couple of places where code assumed wrongly that there would be coordinates.

Obs viewer fails if geometry missing #185412397

---

projects/laji/src/app/shared-modules/own-submissions/service/document.service.ts

https://www.pivotaltracker.com/story/show/185412289
https://185412289.dev.laji.fi/vihko
Old implementation tried to always delete the document through the API. It failed for local documents since they don't exist, resulting in a "hups" and the local doc not being removed.
I fixed the logic to first check if the doc is local one, and accordingly remove it from the local or remote source.

Fix deleting local document [#184661048]

---

projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.html
projects/laji/src/i18n/fi.json

https://186220191.dev.laji.fi/observation/map
https://www.pivotaltracker.com/n/projects/2346653/stories/186220191
Now the map close-button is aligned to left, shown in primary color, and has the correct title.

Map close-button fixes [#186220191]

---

angular.json
projects/bird-atlas/src/index.prod.html
projects/iucn/src/index.html
projects/iucn/src/index.prod.html
projects/kerttu-global/src/index.prod.html
projects/laji/src/index.prod.html

Production and dev environments now use different `index.html` files and plausible is only included in production.
https://www.pivotaltracker.com/story/show/185842878

Use plausible in prod only

---

projects/laji/src/app/shared-modules/document-viewer/images/images.component.ts
projects/laji/src/app/shared/gallery/gallery/gallery.component.html
projects/laji/src/app/shared/gallery/gallery/gallery.component.ts
projects/laji/src/app/shared/gallery/image-gallery/image-modal.component.ts

https://186078537.dev.laji.fi/observation/images
https://www.pivotaltracker.com/n/projects/2346653/stories/186078537
Now the image tab's view mode (large images or small images) persists after changing the paginator page. This is done by emitting the view state to parent. Also ViewType is implemented in this PR as a refactor.

Image tab mode persists [#186078537]

---

projects/laji-ui/src/lib/modal/modal/modal.component.ts

Currently the modal hides itself on construction. This can cause it to remove body's overflow. This PR makes the body overflow control more fine-grained: modal construction hides the main element, but doesn't touch body overflow until the modal is actually shown. Then, the modal "hijacks" the body overflow, and "releases" it when it hides.

Fix modal doesn't touch body overflow if it's not been hijacked yet

---

projects/laji-ui/src/lib/sidebar/sidebar.component.ts
projects/laji/src/app/+project-form/form/laji-form/laji-form-footer/laji-form-footer.component.ts
projects/laji/src/app/root/platform.service.ts
projects/laji/src/app/shared-modules/info/info/info.component.ts

Found during SSR testing that these references to `window` made the SSR crash.
The `window` should be accessed through the platform browser, because it's not in node API.

Fix window references

---

projects/laji-ui/src/lib/sidebar/sidebar.component.ts

I honestly don't know what's going on with hydration + animations. Why are animations played on the server at all? Anyways, the animation was being stuck in the "closed" state... this change just makes sure that the "open" state is the inverse of the closed state. Seems to fix the issue. Although do note that it does look a bit strange that the navbar starts from the closed state on the SSR version and then opens up when js loads on the client. Kinda weird, but idk what to do about that.

Fix sidebar animation in ssr hydration

---

.eslintrc.js
projects/bird-atlas/.eslintrc.json
projects/exhibition-screen/.eslintrc.json
projects/iucn/.eslintrc.json
projects/kerttu-global/.eslintrc.json
projects/label-designer-electron/.eslintrc.json
projects/label-designer-element/.eslintrc.json
projects/label-designer/.eslintrc.json
projects/laji-ui/.eslintrc.json
projects/vir/.eslintrc.json

Running neovim on windows eslint was unable to find tsconfig (it thought that the root directory was at the location of the current file...). Unfortunately I was not able to find a fix that doesn't touch project files, but I don't think this fix should break anything.

Fix eslint not finding tsconfig on some systems

---

projects/laji/src/app/+observation/form/observation-form.component.html
projects/laji/src/app/+observation/form/observation-form.component.ts
projects/laji/src/app/+observation/form/own-observations-filter/own-observations-filter.component.ts

https://185803929.dev.laji.fi/observation/list
https://www.pivotaltracker.com/n/projects/2346653/stories/185803929
The observer is not -filter ("exclude") clears both "as observer" and "as editor" filters properly.

Fix "Observer is not" filter [#185803929]

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-overview.component.html

https://185825107.dev.laji.fi/taxon/MX.63082
https://www.pivotaltracker.com/n/projects/2346653/stories/185825107
The scientific name column in subtaxon rows links to the subtaxon's page. Why scientific name and not vernacular name? Because it could be fixed with a one-liner and not all taxa have vernacular names (common in fungi).

Subtaxon row links [#185825107]

---

projects/laji-ui/src/lib/_utils.scss
projects/laji/src/app/+project-form/form/laji-form/laji-form-footer/laji-form-footer.component.html
projects/laji/src/app/+project-form/form/laji-form/laji-form-footer/laji-form-footer.component.scss

https://186579462.dev.laji.fi/project/JX.519/form
https://www.pivotaltracker.com/n/projects/2346653/stories/186579462
Removed empty spaces between the save buttons and used no-wrap to prevent text overflow on small screens.

Fix save button text overflow [#186579462]

---

projects/laji/src/app/+project-form/form/named-place/named-place/named-place.component.html
projects/laji/src/app/+project-form/form/named-place/named-place/named-place.component.ts

Currently the named places filtering works kind of accidentally. Let's look at the invasive species named places view for example:
https://dev.laji.fi/en/project/MHL.33/form/places
If you select some municipality, and then again 'All municipalities', the API query will have `&municipality=all`. The old API has some logic that filters non QNames for some query params. It's implemented in a very messy way, and I also just don't agree that we should do that in the API. So, in the new API I'm not going to do that kind of filtering for the params - if anything, I'd rather throw an exception for a bad query param. But I don't think that's really necessary. So, this PR fixes the query so that it won't have `municipality=all`. Instead, there just won't be a municipality filter (same as all). …

Named places 'all' filter as empty to API query

---

projects/laji/src/app/shared-modules/document-viewer/document/document.component.ts

Task: https://www.pivotaltracker.com/story/show/186261663, testable here: https://186261663.dev.laji.fi/.
Solving this required adding a query to form endpoint to read the field denoting a form as member of secondary collection, which I'm not too keen on.

Modify-button visible for secondary data #186261663

---

projects/iucn/src/environments/environment.prod.ts
projects/iucn/src/environments/environment.ts
projects/kerttu-global/src/environments/environment.dev.ts
projects/kerttu-global/src/environments/environment.prod.ts
projects/kerttu-global/src/environments/environment.ts
projects/laji/src/environments/environment.beta.ts
projects/laji/src/environments/environment.dev-embedded.ts
projects/laji/src/environments/environment.embedded.ts
projects/laji/src/environments/environment.local-beta.ts
projects/laji/src/environments/environment.local-prod.ts
projects/laji/src/environments/environment.local.ts
projects/laji/src/environments/environment.prod.ts
projects/laji/src/environments/environment.ts
projects/vir/src/environments/environment.dev.ts
projects/vir/src/environments/environment.prod.ts
projects/vir/src/environments/environment.ts

The geoserver development instance will no
longer use a reverse proxy and all content
will now be served at the default /geoserver
endpoint.

Update geoserver-dev urls

---

projects/laji/src/app/+project-form-edit/laji-form-builder/laji-form-builder.component.ts
projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.ts
projects/laji/src/app/shared-modules/document-viewer/document/document.component.ts

The document viewer dispalyed the document writable (= shows edit & delete buttons) based on just looking at the form's secondaryCopy option. This made all documents with non-secondaryCopy form display the buttons. I made it to act on the secondaryCopy option only if it's false.
Also removed few unused variables from the document annotation component.

Fix document viewer checking write rights [#187698581]

---

projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts

https://www.pivotaltracker.com/story/show/187698638
https://187698638.dev.laji.fi/observation/map
This is a little difficult to test since the bug doesn't happen every time. It was caused by not unsubscribing the map data subscription before creating a new one.

Fix observation map sometimes showing wrong data

---

projects/laji/src/app/+project-form/form/form.routes.ts
projects/laji/src/app/+project-form/form/named-place-linker/named-place-linker-wrapper.component.ts

https://www.pivotaltracker.com/story/show/187659711
The root reason for this bug is that the project form routing is a bit awkward. It uses a single path param for either a sub form or a document, so I hadn't checked that the routing works also for forms without a sub form.

Fix named place linking for forms without sub forms [fixes #187659711]

---

projects/laji/src/app/+project-form/form/document-form/document-form.facade.ts

https://www.pivotaltracker.com/story/show/187867645

Fix "editors" field being copied to documents from the named place

---

projects/laji-ui/src/lib/typeahead/component-loader/component-loader.class.ts
projects/laji-ui/src/lib/typeahead/component-loader/testing/test-setup.ts
projects/laji-ui/src/lib/typeahead/positioning/positioning.service.ts
projects/laji-ui/src/lib/typeahead/positioning/testing/test-setup.ts
projects/laji-ui/src/lib/typeahead/typeahead-container.component.ts

Basically circumvents the positioning service that was copy pasted from ngx-bootstrap entirely. Instead using the placement service that I wrote some time ago for tooltips/popovers/etc.
The typeahead is an absolute monster. It's difficult to comprehend how it's possible to have thousands of LOC for what amounts to a simple dropdown. It seems really bad performance wise as well. Eg. it doesn't use `OnPush` and I checked that it was calling the positioning logic constantly even when no change was happening...
I added some checks for invalid values, but in practice I never saw them come up when testing. The z-index is to ensure that the dropdown opens on top always (such as on new annotation form).
https://www.pivotaltracker.com/n/projects/2346653/stories/187852117 …

Use laji-ui placement service in typeahead instead of ngx-bootstrap

---

projects/iucn/src/environments/environment.prod.ts
projects/iucn/src/environments/environment.ts
projects/kerttu-global/src/environments/environment.dev.ts
projects/kerttu-global/src/environments/environment.prod.ts
projects/kerttu-global/src/environments/environment.ts
projects/laji/src/environments/environment.beta.ts
projects/laji/src/environments/environment.dev-embedded.ts
projects/laji/src/environments/environment.embedded.ts
projects/laji/src/environments/environment.local-beta.ts
projects/laji/src/environments/environment.local-prod.ts
projects/laji/src/environments/environment.local.ts
projects/laji/src/environments/environment.prod.ts
projects/laji/src/environments/environment.ts

Test that the new url works: go to https://32.dev.laji.fi/theme/protax, switch to the "File selector" tab and upload the [protax-example-10.txt](https://github.com/user-attachments/files/16086135/protax-example-10.txt) file. The new urls are connected to Rahti 2.

Change protax api url

---

projects/laji/src/app/shared/api/PersonApi.ts
projects/laji/src/app/shared/route/only-logged-in.ts
projects/laji/src/app/shared/service/user.service.ts

- Fixes blank page when page should be redirected by the `OnlyLoggedIn` guard
- Fixes logout always erroring, because it was expecting json from the api (though the logout did succeed)
- Refactored user service to use tagged unions to represent loading states

User service fixes

---

projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.ts

https://www.pivotaltracker.com/story/show/186579144
https://186579144.dev.laji.fi/observation/list
Fixed error message for not logged in user or otherwise missing taxon field in annotation view by making element focus call use optional chaining to account for taxon input element possibly being null. Did same for comment field hotkey which could theoretically cause same issue.

Annotation viewer: hotkey alt+t for missing taxon field #186579144

---

projects/laji/src/app/shared-modules/latest-documents/latest-documents.facade.ts
projects/laji/src/app/shared-modules/latest-documents/latest/haseka-users-latest.component.html
projects/laji/src/app/shared-modules/latest-documents/latest/haseka-users-latest.component.ts

https://www.pivotaltracker.com/story/show/187298216
https://187298216.dev.laji.fi/vihko/home
Fixed by hiding the latest documents in sidebar until the latestDocumentFacade is done loading if the call to it is first since page load, to keep documents still in latestDocumentFacade potentially from other projects from showing up. LatestDocumentFacade also could cause page to update with wrong projects documents after pagechange due to hanging subscription to latest documents, so I added unsuscribe call to it when the query changes.

Sidebar displays observations from another form #187298216

---

projects/laji/src/app/shared-modules/spreadsheet/excel-generator/excel-generator.component.ts

https://www.pivotaltracker.com/story/show/185861037
https://185861037.dev.laji.fi/vihko/tools/generate
Changed and simplified adding new columns to excel generation to keep the user defied order.

Adding a new field resets order in excel import generation #185861037

---

projects/laji/src/app/shared-modules/document-viewer/types/type/type.component.html

https://www.pivotaltracker.com/story/show/186895419
https://186895419.dev.laji.fi/view?uri=http:%2F%2Fid.luomus.fi%2FF.16353, under Extra info
Added missing pipe chain to render label for typeVerification value properly.

Use label for MY.typeVerifications on observation viewer #186895419

---

projects/laji/src/app/+user/friends/friends.component.ts

https://www.pivotaltracker.com/story/show/184178674
https://184178674.dev.laji.fi/
Added change detection to clear out the variable locking the button to add a new friend when page changes to a new user, unfortunately now if user uses back button they can resend the request, but that was possible already before via reloading the page.

Cannot add two friends #184178674

---

projects/laji/src/app/+observation/result/observation-result.component.ts

Fixes a bug where you draw a large polygon to the observation map and nothing seems to happen.
Not sure if the catch block has ever worked. I tested the behaviour against the old API, and it doesn't work even there so idk...

fix polygon registration catch block path to error [closes #547]

---

projects/laji/src/app/+user/login/user-login.component.ts

Fix redirection with the `next` parameter not working if the path contains query parameters

Fix redirection with query parameters

---

projects/laji/src/app/shared-modules/download-modal/download.component.ts
projects/laji/src/app/shared-modules/download-request/file-download/file-download.component.html
projects/laji/src/app/shared/service/confirm-modal.component.ts
projects/laji/src/i18n/fi.json

https://www.pivotaltracker.com/story/show/188161910
Adds deprecation notice of the shp format to citable downloads (https://188161910.dev.laji.fi/citation/HBF.11712) and light downloads (https://188161910.dev.laji.fi/observation/list?target=MX.48089)

Shp deprecation notice

---

projects/laji/src/app/+project-form/form/named-place/named-place/named-place.component.ts
projects/laji/src/app/shared/model/FormPermission.ts
projects/laji/src/app/shared/service/form-permission.service.ts

Form permissions logic has changed in the API so that instead of having a hard coded list of which forms are related, the permissions are inherited based on the collectionID.
This broke the laji.fi code for line transect form. I updated the logic based on:
* Form permissions has to be checked always, even though the user is not logged in. Earlier, for unlogged user, the view permissions were checked directly from the form's `MHL.restrictAccess` property. This doesn't work anymore, since the property might be inherited.
* The new API's `/formPermissions/:collectionID` returns `restrictAccess` and `hasAdmins` properties, which are checked with inheritance with mind. So, for example the API returns `{ restrictAccess: "MHL.restrictAccessLoose", hasAdmins: true }` for collectionID `HR.2962`, …

Update form permissions logic according to laji-api changes

---

projects/laji/src/app/+project-form/form/named-place/np-info/np-info.component.ts

Repro:
1. goto http://beta.laji.fi/project/MHL.1/form/MHL.1/places?activeNP=MNP.27447 when unlogged
-> Error is thrown
Fix testable in https://241004.dev.laji.fi/project/MHL.1/form/MHL.1/places?activeNP=MNP.27447
There's something wrong in the user service logic. Even though the `user$` is stated as `Observable<Person | undefined>`, if you look at the actual type of it (hover in you IDE or however you do it), it's just `Observable<Person>`. This is interesting, as I though stating a type has stronger preference than type inference.
There might be similar errors somewhere as the typing is wrong (`user$` can emit `undefined` even though the typing says otherwise), but I don't have time to dig deeper just now.

Fix null pointer error for undefined user in np-info

---

projects/laji/src/app/shared/panel/panel.component.html
projects/laji/src/app/shared/panel/panel.component.ts

Related (copied from slack):
Ramble about angular animations: There have been various issues with the panels including this one, things overlapping on the observation page, taxon info card maps breaking, etc. These are all caused by angular animations (especially in combination with ssr/hydration).
Issues:
1. the SSR generated html includes invalid syntax like style=""height=*;" (this comes from angular animations wildcard).
2. After hydration completes animation state doesn't update even if the predicate changes during hydration
3. Since the animation targets the height property, sometimes the height updates correctly, but no resize event is emitted to child nodes (which breaks the map)
4. Other stuff I guess...
We do have animations on some other components that seem to not have issues …

Fix various bugs with the common panel/accordion component

---

projects/laji/src/app/shared/service/util.service.ts

Fixes bug described in #581
~(waiting for approval still, but I wrote this PR anyway while it's still fresh in my mind)~ (Approved)
The bug appeared with the new API. From the new API's [breaking changes documentation](https://github.com/luomus/laji-api/blob/master/breaking-changes.md):
> Document dateCreated & dateEdited uses zulu date (eg if clock in Finland is 17.25:09 on 21.3.2024, it's 2024-03-21T15:25:09.850Z instead of 2024-03-21T17:25:09+02:00)
This change was introduced because in modern Javascript world, the `Date` API is reliable and consistent across environments. The old API used `moment`, which shouldn't be used anymore. The new API's date format is what `new Date().toISOString()` gives.
`Date()` interprets both formats ok. I tested with `node`:
```
$ node
Welcome to Node.js …
```

Use Date() instead of inhouse date interpretation [fixes #581]

---

projects/laji/src/app/shared-modules/own-submissions/own-datatable/own-datatable.component.ts
projects/laji/src/app/shared-modules/pill-list/pill-list.component.ts
projects/laji/src/app/shared-modules/technical-news/technical-news-dumb/technical-news-dumb.component.ts

Could someone review my first week's strict TS config changes? Not sure what to do in situations where a type is now possibly undefined, and it isn't addressed in the code, (see newline 220 on own-datatable.component.ts, or code in technical-news-dumb.component.ts).

Strict TS config - Week 1

---

projects/laji/src/app/+observation/view/observation-view.component.ts

Removed the modal to inform users of new search functionality by commenting out the code triggering it, for the sake of reusing it later if needed.
Testable here: https://625.dev.laji.fi/

Remove new search functionality modal #625

---

projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-group-select.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-group-select.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list-breadcrumb/informal-list-breadcrumb.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list-breadcrumb/informal-list-breadcrumb.component.ts
projects/laji/src/app/shared-modules/extended-group-select/extended-group-select.component.ts
projects/laji/src/app/shared-modules/extended-group-select/observation-extended-group-select.component.ts
projects/laji/src/app/shared/api/InformalTaxonGroupApi.ts
projects/laji/src/app/shared/group-select/group-select.component.ts
projects/laji/src/app/shared/group-select/observation-group-select.component.ts
projects/laji/src/app/shared/model/ArrayResult.ts
projects/laji/src/app/shared/service/util.service.ts

* Use `informal-taxon-groups/:id/parent` instead of `informal-taxon-groups/:id/parents` (reasoning in
https://github.com/luomus/laji-api/issues/51)
* Refactor informal taxon groups client
* Fix null pointer error in `informal-list-breadcrumb` (currently broken in https://beta.laji.fi/taxon/browse?informalGroupFilters=MVL.342 - open the console and there are errors spitted)
Closes #700

Refactor informal taxon groups usage according to api changes

---

projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.ts

Removes usage of the job status `documents` property. Currently it seems to try to validate the API response that it has correct length for the documents. We should just trust the API for this, no need to carry the documents over the job status check.

Remove document batch upload checking job status documents

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-taxonomy/taxon-taxonomy.component.scss

Remove capitalization because it capitalizes words that should begin with lowercase, e.g. "ex".

Remove taxon author name capitalization

---

projects/laji/src/app/+home/home.component.html
projects/laji/src/app/graph-ql/graph-ql.module.ts
projects/laji/src/app/graph-ql/service/base-data.service.ts
projects/laji/src/app/graph-ql/service/graph-ql.service.ts
projects/laji/src/app/shared/api/WarehouseApi.ts

#714
Reduces the number of queries in ssr to data warehouse by
- removing all graphql queries in the server
- removing all queries to `warehouse` endpoint in the server (most were already removed)
- hides the publications section in the front page in the server

Reduce ssr dw queries

---

projects/laji/src/app/shared-modules/spreadsheet/service/augment.service.ts

closes #568 
https://568.dev.laji.fi/project/MHL.1136/import
The excel import augments the documents with named place data if they contain named place ids. This previously worked for `gathering`-level named places, now it also works for `document`-level places.

Excel import named place

---

projects/laji/src/app/+taxonomy/browse-species/browse-species.component.html
projects/laji/src/app/+taxonomy/browse-species/browse-species.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-group-select.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-group-select.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list-breadcrumb/informal-list-breadcrumb.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list-breadcrumb/informal-list-breadcrumb.component.ts
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list/informal-list.component.html
projects/laji/src/app/+taxonomy/browse-species/informal-group-select/informal-list/informal-list.component.ts
projects/laji/src/app/+taxonomy/species/service/taxonomy-columns.ts
projects/laji/src/app/+taxonomy/species/species-list/species-list.component.ts
projects/laji/src/app/shared-modules/datatable/datatable-templates/datatable-templates.component.html

https://696.dev.laji.fi/taxon/browse?informalGroupFilters=MVL.343
https://github.com/luomus/laji/issues/696
Three changes:
1. Made the "informal-list-breadcrumb" links (the path Kaikki / Putkilokasvit... etc.) clickable with right mouse button so that they can be opened to a new tab. This can be done by adding [routerLink], and taxon id as [queryParams].
2. Made the "informal-list" buttons clickable with the same method.
3. Used cell-template 'taxonScientificNameLink' for the list's scientificName column and changed the cell-template to check whether row.id is a link or id, and form the [routerLink] accordingly. It should therefore work with taxa and subordinate taxa.

Apply links to browse taxon -page [closes #696]

---

projects/bird-atlas/src/app/+bird-society/bird-society-info/bird-society-info.component.ts
projects/laji-ui/src/lib/directives/fill-height.directive.ts
projects/laji-ui/src/lib/dropdown/dropdown-toggle.directive.ts
projects/laji-ui/src/lib/sidebar/sidebar.component.ts
projects/laji-ui/src/lib/tabs/tab/tab.component.ts
projects/laji/src/app/shared/service/browser.service.ts
projects/laji/src/app/shared/service/util.service.ts
projects/vir/src/app/component/global-message/global-message.component.ts

The notifications dropdown uses virtual scrolling from angular cdk, which needs to get a resize event whenever its container is resized. Whenever the dropdown is activated the dropdown menu goes from `display: none` to `block` and so is effectively resized `(0,0) -> (x,y)`. Sending a resize event ensures that the virtual scrolling viewport is aware of this change and can update the number of visible elements accordingly
Also extracted the dispatch resize event function into utils, and refactored other parts of the project to use it

Dispatch resize event on dropdown toggle [Fixes #570]

---

projects/laji/src/app/+observation/form/date-form/date-form.component.html

#706
https://706.dev.laji.fi/observation/list
Fix just adds a missing parameter to datepicker which sets it to last day of the year.

Fix incorrect end date interpretation on observation search

---

projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.html
projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.ts
projects/laji/src/environments/global.ts

#616
https://616.dev.laji.fi/observation/list?sourceId=KE.901&recordQuality=COMMUNITY_VERIFIED
Community verified tag could not be removed with annotations, fixed by enabling an commented out section of code and adding community verified tag to trigger the allowed tag removal clauses.

Fix community verified tag cannot be removed with annotation

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.ts
projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.facade.ts

#738
https://738.dev.laji.fi/taxon/MX.51278/identification
Added cleanup function to onChange event handler to clear taxon description and author data which might contain old data when taxon changes to one which doesn't contain data to overwrite it with.

Fix taxon page showing incorrect text source

---

projects/laji/src/app/shared-modules/own-submissions/service/document-export.service.ts

https://739.dev.laji.fi/
https://github.com/luomus/laji/issues/739
When downloading own Vihko submissions, print a warning to the console if there are invalid geometries but don't fail the whole download.

Fix invalid geometry prevents loading own submissions

---

projects/laji/src/app/shared-modules/document-viewer/document/document.component.ts

Fixes the document viewer when a document has formId that doesn't exist.
Repro:
https://beta.laji.fi/observation/list?collectionId=HR.128&collectionIdNot=HR.173,HR.447,HR.160,HR.129,HR.48,HR.203,HR.93
Click some of the observation table rows to show the viewer. It says not loaded to warehouse, while you can see from the
network tab that it's loaded.

Fix document viewer for unknown form

---

projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-info/taxon-info.component.html

Removes the grey placeholder block from DNA-barcode section if none exists.
Test branch here https://809.dev.laji.fi/, task #809

Fix broken dna barcode link 809
