luomus/laji

- projects/laji/src/app/shared-modules/laji-form/laji-form-document.facade.ts
- projects/laji/src/environments/global.ts
Completes https://www.pivotaltracker.com/story/show/170209611
> Add profile personal collection code to document form

- projects/laji/src/styles/laji.scss
Completes task #176609954
Scrollbar default width is restored to default. I also did small changes to scrollbar colors to more closely align it with the theming of the site.
> improve scrollbar accessibility

- projects/laji/src/app/+observation/result/observation-result.component.html
- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.component.ts
- projects/laji/src/app/shared-modules/observation-result/observation-year-chart/observation-year-chart.component.ts
Solve problem onlyCount variable. Now calling always false the first time, later taking data from previous result.
Solve problem label ObservationMonthDayChartComponent. It used subscribe to get label chart data, but it had to be observable
> Charts not working individual count #176667352

- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts
…rvation/map" do not preserve "/en" [#176780949]
> Fix "Show additional information" links not preserving lang in map dialog

- projects/laji/src/app/shared-modules/laji-form/document-form-header/document-form-header.component.html
- projects/laji/src/app/shared-modules/laji-form/document-form-header/document-form-header.component.ts
When multiple municipalities, areas were not converted to name
> convert multiple area codes - [176759772]

- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts
Fixes the issue where map isn't showing updated results if toggling a filter that shows results -> shows no results -> shows results
Demo at [176854094.dev.laji.fi](https://176854094.dev.laji.fi)
> Fix observation map does not show results [#176854094]

- projects/laji/src/app/shared-modules/taxon-select/taxon-select.component.ts
Testable [here](https://176904971.dev.laji.fi)
> Taxon cannot be deselected [fixes #176904971]

- projects/laji/src/app/shared-modules/document-viewer/row/row.component.scss
This makes sure that no label can overlap with value in the viewer
> Fix field labels overlap with value [#177135951]

- package-lock.json
- package.json
- projects/laji/src/styles/laji.scss
Testable @ https://177198860.dev.laji.fi/
> Disable bootstrap button override 177198860

- projects/iucn/src/app/+about/about.component.ts
- projects/laji/src/app/+project-form/about/about.component.html
- projects/laji/src/app/+project-form/instructions/instructions.component.ts
- projects/laji/src/app/+theme/emk/emk.component.html
- projects/laji/src/app/+theme/genetic-resource/instructions/genetic-resource-instructions.component.html
- projects/laji/src/app/+theme/kerttu/kerttu-instructions/kerttu-instructions.component.html
- projects/laji/src/app/+theme/protax/protax.component.html
- projects/laji/src/app/shared-modules/info-page/info-page.component.ts
- projects/laji/src/app/shared-modules/laji-form/document-form/document-form.component.html
- projects/laji/src/app/shared/model/Information.ts
- projects/laji/src/app/shared/model/InformationItem.ts
this changes the inputs and outputs of info-page component to be little more logical.
Testable @ https://177217010.dev.laji.fi
> Rafactor InfoPageComponents [#177217010]

- projects/laji/src/app/+project-form/form/named-place/np-choose/np-list/np-list.component.ts
Testable at https://177301350.dev.laji.fi/
> Fixes rows disappear from namedplace select table [#177301350]

- package-lock.json
- package.json
This can be tested only in beta env, so I'll merge this right away, test it and revert the changes if they don't work.
> Laji-form hacks removed that have fixed some issues with prod build

- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
hide onlyFinnish value from taxon search pages filters
Testable at https://176981600.dev.laji.fi
> skip onlyFinnish value in taxon species form [#176981600]

- projects/laji/src/app/+observation/form-sample/form-sample.component.html
Add datasets to genomic resources collection theme page.
Testable at https://177558929.dev.laji.fi/theme/luomusgrc/search/list
> Add taxonomic datasets to grc theme page search filter 177558929

- projects/laji/src/app/+theme/kerttu/audio-viewer/audio-info/audio-info-map/audio-info-map.component.ts
- projects/laji/src/app/shared-modules/laji-map-noop/laji-map.interface.ts
- projects/laji/src/app/shared-modules/laji-map/laji-map.interface.ts
Fixes a problem that causes theme pages (https://beta.laji.fi/theme) load very slowly.
> Fix SSR error on theme pages

- projects/laji/src/app/+project-form/form/named-place/np-choose/np-map/np-map.component.ts
- projects/laji/src/app/shared/model/Form.ts
Implements named place option `MHL.mapCluster` to cluster the points on named places choosing map view.
Demo: https://177759644.dev.laji.fi/project/MHL.65/form/MHL.65/places
This needs to be on included on the next release 41!
> Named places map clustering [#177759644]

- projects/laji/src/app/shared/pipe/label.pipe.ts
this fixes the pill list not showing written names in Luomus GRC theme page testable
https://177758215.dev.laji.fi/en/theme/luomusgrc/search/list
> Label pipe should return the key when no value found [#177758215]

- projects/laji/src/app/+theme/kerttu/audio-viewer/audio-info/audio-info.component.scss
- projects/laji/src/app/+theme/kerttu/audio-viewer/audio-viewer.component.html
- projects/laji/src/app/+theme/kerttu/audio-viewer/audio-viewer.component.scss
- projects/laji/src/app/+theme/kerttu/kerttu-letter-annotation/letter-annotation/letter-annotation.component.html
- projects/laji/src/app/+theme/kerttu/kerttu-letter-annotation/letter-annotation/letter-annotation.component.scss
- projects/laji/src/app/+theme/kerttu/kerttu-recording-annotation/kerttu-occurrence-table/kerttu-occurrence-table.component.html
- projects/laji/src/app/+theme/kerttu/kerttu.component.ts
Testable [here](https://177776349.dev.laji.fi/theme/kerttu/letters). Fixes these issues with Kerttu buttons:
- "I don't know" button is smaller than the others
- Time and place text is not aligned with audio viewer buttons
- Active audio viewer buttons look weird
> fix kerttu buttons style

- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.html
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.scss
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.ts
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.component.ts
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/taxon-identification.facade.ts
Fixes all identification issues found on wednesday 14th
> Identification fixes #177758816

- package-lock.json
- package.json
No need for review here, since it's just a package update. PR for documentative purposes.
Adds toggle mode to Vihko boolean fields. The mode is active, if:
* the labels aren't default "yes"/"no"
* button for undefined isn't displayed
The toggle mode has the following effects:
* hides the label of the inactive button
* clicking the inactive button toggles the value
> Vihko boolean fields new styling [177758565]

- projects/laji-ui/src/lib/_buttons.scss
- projects/laji-ui/src/lib/mixins/_buttons.scss
- projects/laji/src/styles/bs_overwrites.scss
subtle global improvements to button styles
> refine button active state styles

- projects/laji/src/app/graph-ql/service/base-data.service.ts
- projects/laji/src/app/shared-modules/datatable/service/datatable-util.service.ts
- projects/laji/src/app/shared-modules/document-viewer/observation-effective-tags-taxon/observation-effective-tags-taxon.component.ts
- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.component.ts
- projects/laji/src/app/shared/pipe/label.pipe.ts
- projects/laji/src/app/shared/pipe/warehouse.pipe.ts
- projects/laji/src/app/shared/service/warehouse-value-mapping.service.ts
Unfortunately this cannot be tested in dev but the impact is testable at https://177896280.dev.laji.fi/
(this also contains renaming `getOriginalKey` to `getSchemaKey`)
> Fix missing labels in viranomaiset [177896280]

- projects/laji/src/app/+home/home.component.html
> Fix frontpage iNat link

- projects/laji/src/app/shared-modules/info-page/info-page.component.ts
Testable on this page: https://177961515.dev.laji.fi/project/MHL.69/about. Previously info page showed a loading placeholder also when it had loaded the content but the content was empty.
> Don't show info page placeholder if no content

- projects/laji/src/app/+theme/protax/protax-api.ts
- projects/laji/src/app/+theme/protax/protax-form/protax-form.component.html
- projects/laji/src/app/+theme/protax/protax-form/protax-form.component.ts
- projects/laji/src/app/+theme/protax/protax.component.ts
Testable [here](https://177202324.dev.laji.fi/theme/protax). A file input is cleared after submitting it to reduce situations where user submits a modified file which causes problems on some browsers.
> Protax submit fails when submitting a modified file

- projects/laji/src/app/+taxonomy/species/species-form/species-form-query.interface.ts
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.ts
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
- projects/laji/src/app/shared-modules/select/select/select.component.html
- projects/laji/src/app/shared-modules/select/select/select.component.ts
The problem is happening inside metadata-select. When user click some checkbox, if a checkbox with filter has some option checked, it will open automatically
> Auto opening selects are hiding others

- projects/laji/src/app/shared-modules/spreadsheet/service/mapping.service.ts
This allows ETRS-TM35FIN grid coordinates on excel-import
testable at https://176397033.dev.laji.fi
> Allow ETRS-TM35FIN grid coordinates on excel-import [#176397033]

- projects/laji/src/app/+taxonomy/species/species-form/species-form-query.interface.ts
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.ts
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
- projects/laji/src/app/shared-modules/select/select/select.component.html
- projects/laji/src/app/shared-modules/select/select/select.component.ts
Reverts luomus/laji#102
Bug found see https://www.pivotaltracker.com/story/show/177759152/comments/224102986 for more information
> Revert "Auto opening selects are hiding others"

- projects/laji/src/app/shared-modules/datatable/service/observation-table-column.service.ts
https://www.pivotaltracker.com/story/show/175492882
> hide lajiGIS fields from laji.fi

- projects/laji/src/app/shared-modules/spreadsheet/service/mapping.service.ts
> Revert "Allow ETRS-TM35FIN grid coordinates on excel-import [#176397033]"

- projects/laji/src/app/+project-form/project-form.component.ts
- projects/laji/src/app/+theme/theme-routing.module.ts
- projects/laji/src/app/shared-modules/laji-form/document-form-header/document-form-header.component.ts
Testable [here](https://177961636.dev.laji.fi/theme/datasets). Adds custom html titles to data bank pages.
> Data bank html titles 177961636

- projects/laji/src/app/shared-modules/own-submissions/own-submissions.component.ts
Testable [here](https://177999516.dev.laji.fi).
Steps to reproduce the bug are described in [this pivotal task](https://www.pivotaltracker.com/story/show/177999516).
> Fix own submissions table not showing data

- projects/laji-ui/src/lib/mixins/_base.scss
- projects/laji-ui/src/lib/mixins/_buttons.scss
- projects/laji/src/app/+home/home.component.html
- projects/laji/src/app/+home/home.component.scss
- projects/laji/src/app/+theme/bibliography/bibliography.component.ts
- projects/laji/src/app/shared-modules/info/info/info.component.html
- projects/laji/src/app/shared-modules/info/info/info.component.scss
- projects/laji/src/styles/laji.scss
- projects/laji/src/styles/publications.scss
https://www.pivotaltracker.com/story/show/177868807
https://www.pivotaltracker.com/story/show/178017664
https://178017664.dev.laji.fi/
> Fix scientific articles and frontpage button styles 178017664

- projects/laji/src/app/shared-modules/datatable/datatable-own-submissions/datatable-own-submissions.component.html
- projects/laji/src/app/shared-modules/latest-documents/latest/short-document.component.html
- projects/laji/src/app/shared-modules/latest-documents/latest/short-document.component.ts
- projects/laji/src/app/shared-modules/own-submissions/own-datatable/own-datatable.component.html
https://www.pivotaltracker.com/story/show/177889264
https://177889264.dev.laji.fi/
also fixes: https://www.pivotaltracker.com/story/show/177593502 (seems to be duplicate task)
> Change some vihko buttons to links 177889264

- projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.ts
- projects/laji/src/app/shared-modules/spreadsheet/importer/status-cell/error-list/error-list.component.css
- projects/laji/src/app/shared-modules/spreadsheet/importer/status-cell/error-list/error-list.component.ts
- projects/laji/src/app/shared/service/util.service.ts
Show store error  messages from store if there was one and fake file loaders progress bar 
Testable at https://178242917.dev.laji.fi
> Handle new store errors and bulk upload 178242917

- projects/laji/src/app/+taxonomy/species/species-form/species-form-query.interface.ts
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.ts
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
- projects/laji/src/app/shared-modules/select/select/select.component.html
- projects/laji/src/app/shared-modules/select/select/select.component.ts
This reverts the luomus/laji#118 revert
> Revert "Revert "Auto opening selects are hiding others""

- projects/laji-ui/src/lib/_vars.scss
- projects/laji/src/app/shared-modules/laji-form/document-form-footer/document-form-footer.component.html
button sizes in vihko form bottom save buttons
https://177868169.dev.laji.fi/project/JX.519/form
> Btn size and warning color adjustment #177868169

- projects/laji/src/app/+theme/theme.component.html
- projects/laji/src/i18n/en.json
- projects/laji/src/i18n/fi.json
- projects/laji/src/i18n/sv.json
Testable @ https://177977086.dev.laji.fi/theme
> Add theme nav link for gis documentation

- projects/laji/src/app/+project-form/form/named-place/np-choose/np-choose.component.html
- projects/laji/src/app/shared-modules/datatable/datatable/datatable.component.ts
Testable here: https://178263274.dev.laji.fi
Fixes a bug described here: https://www.pivotaltracker.com/story/show/178263274
> Fix np list displaying wrong item 178263274

- projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.ts
Remove option to save all observations to separate documents testable at [177342074.dev.laji.fi](https://177342074.dev.laji.fi)
> Change the combining default value for imports  [#177342074]

- projects/laji/src/app/+taxonomy/species/species-form/species-form-query.interface.ts
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.ts
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
- projects/laji/src/app/shared-modules/select/select/select.component.html
- projects/laji/src/app/shared-modules/select/select/select.component.ts
Reverception continues. This time we had to manually revert all the changes, since automatic reverting failed.
> Revert "Revert "Revert "Auto opening selects are hiding others"""

- projects/laji/src/app/shared-modules/select/select/select.component.html
- projects/laji/src/app/shared-modules/select/select/select.component.scss
https://www.pivotaltracker.com/story/show/178569767
https://178569767.dev.laji.fi/
> reposition info button in select component

- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.ts
https://www.pivotaltracker.com/story/show/178328958
https://178328958.dev.laji.fi/
> Fix identification image modal indexing bug

- projects/laji/src/app/+project-form/submissions/statistics/common/accepted-document-approval/accepted-document-approval.component.html
- projects/laji/src/app/+project-form/submissions/statistics/common/accepted-document-approval/accepted-document-approval.component.ts
Broken @ http://beta.laji.fi/project/MHL.27/submissions/JX.131450
Fixed @ http://178540272.dev.laji.fi/project/MHL.27/submissions/JX.131450
> Fix accepted document approval for non-json accepted document [#178540272]

- projects/iucn/src/app/+taxonomy/info-card/info-card.component.ts
- projects/laji/src/app/+haseka/haseka.component.ts
- projects/laji/src/app/+information/information.component.ts
- projects/laji/src/app/+news/news.component.ts
- projects/laji/src/app/+observation/observation.component.ts
- projects/laji/src/app/+save-observations/save-observations.component.ts
- projects/laji/src/app/+taxonomy/taxon/info-card/info-card.component.ts
- projects/laji/src/app/+taxonomy/taxon/taxon.component.ts
- projects/laji/src/app/shared-modules/app-component/app.component.ts
- projects/laji/src/app/shared/service/header.service.ts
https://www.pivotaltracker.com/story/show/175113296
https://175113296.dev.laji.fi/
> Improve social media previews

- projects/laji/src/app/+project-form/about/about.component.html
- projects/laji/src/app/+project-form/project-form.module.ts
- projects/laji/src/app/+save-observations/save-observations.component.html
- projects/laji/src/app/+save-observations/save-observations.module.ts
https://www.pivotaltracker.com/story/show/178357999
https://178357999.dev.laji.fi/
> Add technical news to save-observations and projects pages #178357999

- projects/laji/src/app/+observation/abstract-observation.ts
- projects/laji/src/app/+observation/observation.component.ts
https://www.pivotaltracker.com/story/show/178513384
https://178513384.dev.laji.fi/
> Observation subscribe to query params #178513384

- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-info/taxon-info.component.html
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/178262471
https://178262471.dev.laji.fi/
> Add bold info to taxon card

- projects/laji/src/app/+theme/identify/identify.component.ts
Build branch: https://179317838.dev.laji.fi/
> Fixed annotation bug in identification view.

- projects/laji/src/app/+observation/download/observation-download.component.ts
This PR was forgotten from last release (or perhaps it mysteriously disappeared??)
https://177718736.dev.laji.fi/
https://www.pivotaltracker.com/story/show/177718736
> Remove timeout from download approval request toasts

- projects/laji/src/app/+observation/form/date-form/date-form.component.ts
branch build https://179384590.dev.laji.fi/
> Added a use of abs-function to fix incorrect handling of negative values.

- projects/laji-ui/src/lib/tabs/tabs.component.ts
https://www.pivotaltracker.com/story/show/179494369
https://179494369.dev.laji.fi/
> tabs shouldn't emit when responding to content change

- projects/laji-ui/src/lib/tabs/tabs.component.ts
- projects/laji/src/app/+observation/form-sample/form-sample.component.html
- projects/laji/src/app/+observation/form/date-form/date-form.component.html
- projects/laji/src/app/+observation/form/date-form/date-form.component.ts
- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.scss
- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/app/+observation/observation.facade.ts
- projects/laji/src/app/+observation/view/observation-view.component.html
- projects/laji/src/app/+observation/view/observation-view.component.ts
https://www.pivotaltracker.com/story/show/179489448
https://179489448.dev.laji.fi/
> Remove advanced mode from observation search filters

- projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-result-filters/syke-insect-result-filters.component.ts
- projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-result.service.ts
- projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-route-table/syke-insect-route-table.component.ts
- projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-route/syke-insect-route.component.html
- projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-route/syke-insect-route.component.ts
- projects/laji/src/app/+project-form/results/syke-insect-result/syke-insect-routes/syke-insect-routes-list/syke-insect-routes-list.component.ts
Branch at this point contains some bugfixes for the result services which would be good to merge now, but some tasks are not done, but they can be merged in a different pull request later. Branch build here: https://179339504.dev.laji.fi/, pivotal task with bug descriptions here: https://www.pivotaltracker.com/story/show/179339504
> Butterfly and bumblebee census result services improvements

- projects/laji/src/app/shared/pipe/to-qname.pipe.ts
- projects/laji/src/app/shared/service/pdf-label.service.ts
- projects/laji/src/app/shared/service/publication.service.ts
- projects/laji/src/app/shared/service/source.service.ts
- projects/laji/src/app/shared/service/taxon-autocomplete.service.ts
- projects/laji/src/app/shared/service/toasts.service.ts
- projects/laji/src/app/shared/service/triplestore-label.service.ts
- projects/laji/src/app/shared/service/user.service.ts
- projects/laji/src/app/shared/service/util.service.ts
- projects/laji/src/app/shared/taxon-name/taxon-name.component.html
- projects/laji/src/app/shared/taxon-name/taxon-name.component.ts
- projects/laji/src/app/storage/document.storage.ts
There will be many similar PRs coming, read the pivotal story. This PR adds some typings and minor cleaning for the stricter tsconfig to pass.
> Stricter typing [#180206625]

- projects/laji-ui/src/lib/sidebar/sidebar-link/sidebar-link.component.ts
- projects/laji/src/app/+project-form/form/document-form/document-form.facade.ts
- projects/laji/src/app/+project-form/form/named-place-linker/named-place-linker.component.ts
- projects/laji/src/app/+project-form/project-form.service.ts
- projects/laji/src/app/+project-form/submissions/statistics/line-transect/line-transect-chart/line-transect-chart.component.ts
- projects/laji/src/app/+taxonomy/taxon/taxon.component.ts
- projects/laji/src/app/+theme/kerttu/audio-viewer/audio-spectrogram/audio-spectrogram.component.ts
- projects/laji/src/app/+theme/kerttu/audio-viewer/service/audio.service.ts
- projects/laji/src/app/+theme/kerttu/kerttu-recording-annotation/recording-annotation/recording-annotation.component.ts
- projects/laji/src/app/shared-modules/app-component/app.component.ts
- projects/laji/src/app/shared-modules/select/select-subcategories/select-subcategories.component.ts
- projects/laji/src/app/shared-modules/spreadsheet/service/import.service.ts
- projects/laji/src/app/shared-modules/ykj/service/ykj.service.ts
- projects/laji/src/app/shared/directive/click-out-side.directive.ts
- projects/laji/src/app/shared/local-db/local-db.abstract.ts
- projects/laji/src/app/shared/pipe/users.pipe.ts
- projects/laji/src/app/shared/service/coordinate.service.ts
- projects/laji/src/app/shared/service/history.service.ts
- projects/laji/src/app/shared/service/util.service.ts
- tsconfig.json
Enables the `strictFunctionTypes` tsc rule.
There's a couple of `any`'s related to third party libraries that I didn't know how to type...
> Strict function types 180206625

- projects/laji/src/app/shared-modules/spreadsheet/service/file.service.ts
- projects/laji/src/app/shared/model/NamedPlace.ts
- projects/laji/src/app/shared/service/id.service.ts
- projects/laji/src/app/shared/service/laji-api.interceptor.ts
- projects/laji/src/app/shared/service/laji-api.service.ts
- projects/laji/src/app/shared/service/laji-title.ts
- projects/laji/src/app/shared/service/named-places.service.ts
> More strict typing [#180206625]

- projects/laji/src/app/+project-form/project-form.component.scss
https://180278890.dev.laji.fi/project/MHL.3/stats?tab=species
> fix project form sidebar height issues

- projects/laji/src/app/locale/localize-router.service.ts
- projects/laji/src/app/locale/localize.guard.ts
- projects/vir/src/app/component/global-message/global-message.component.ts
The added strict type rules in last update broke vir builds. This PR fixes those errors
> fix vir type errors

- projects/laji/src/app/shared-modules/taxon-autocomplete/taxon-autocomplete.component.html
- projects/laji/src/app/shared-modules/taxon-autocomplete/taxon-autocomplete.component.ts
https://www.pivotaltracker.com/story/show/180148293
> fix nullcheck & eventhandler leak

- projects/laji/src/app/shared-modules/observation-result/observation-table/observation-table.component.ts
https://www.pivotaltracker.com/story/show/180765737
https://180765737.dev.laji.fi/
> Fix observation table sorting

- projects/laji/src/app/+observation/form/conservation-filter/conservation-filter.component.html
- projects/laji/src/app/+observation/form/conservation-filter/conservation-filter.component.ts
- projects/laji/src/app/+observation/form/observation-form-query.interface.ts
- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/app/+observation/observation-component.module.ts
- projects/laji/src/app/+observation/search-query.service.ts
- projects/laji/src/app/shared/model/WarehouseQueryInterface.ts
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/180584625
https://180584625.dev.laji.fi/
> Observation filters: conservation

- projects/laji/src/app/+observation/form/observation-form.component.ts
> taxonAdminFiltersOperator is only used when it's OR

- projects/laji/src/app/+save-observations/save-observations.facade.ts
- projects/laji/src/environments/global.ts
https://www.pivotaltracker.com/story/show/181151175
https://181151175.dev.laji.fi/save-observations
The goal being that bird atlas form is shown first. I added a hard coded order list, which is read so that forms not found in the list are ordered by ID after the ones from the order list.
> Add hard coded form category order list [#181151175]

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/app/+observation/observation.component.ts
- projects/laji/src/i18n/fi.json
- projects/vir/src/environments/environment.dev.ts
- projects/vir/src/environments/environment.prod.ts
- projects/vir/src/environments/environment.ts
https://www.pivotaltracker.com/story/show/180597998
https://www.pivotaltracker.com/story/show/180598385
https://viranomaiset-dev.laji.fi/observation/list
(to be approved)
> PAP ELY search

- projects/laji/src/app/+observation/form/conservation-filter/conservation-filter.component.html
- projects/laji/src/i18n/fi.json
(no pivotal task)
https://73565643.dev.laji.fi/ should pop up soon
> add laji-info to taxonAdminFiltersOperator filter

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/i18n/fi.json
(no pivotal task)
no preview atm unfortunately either :(
> add virva shortcut info

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/vir/src/app/component/footer/footer.component.ts
* Adds Virva info page link to footer and relevant btn info box
* some other info page links to footer
(no pivotal task)
> add multiple vir info pages

- projects/laji/src/app/+taxonomy/taxon/info-card/shared/service/info-card-query.service.ts
https://www.pivotaltracker.com/story/show/181308710
https://181308710.dev.laji.fi/
> Add source id parameter to info card specimen queries

- projects/laji/src/app/shared-modules/spreadsheet/service/spreadsheet.service.ts
Trim white spaces when loading excel sheet
https://181416108.dev.laji.fi/vihko/tools/import
https://www.pivotaltracker.com/story/show/181416108
> Trim whitespaces on excel import

- projects/laji/src/app/+observation/observation-data.service.ts
- projects/laji/src/app/+observation/observation.facade.ts
Change species count query so that the count is the same than the total count in the species table
https://181420427.dev.laji.fi/observation/species
> Species count query changes

- projects/laji/src/app/shared-modules/document-viewer/unit-rows/unit-rows.component.html
Testable here: https://180961690.dev.laji.fi/observation/list
> Add atlas code and class to document viewer

- projects/laji/src/app/+project-form/form/named-place-linker/named-place-linker.component.ts
- projects/laji/src/app/+project-form/guards/abstract-permission-guard.ts
- projects/laji/src/app/+project-form/results/wbc-result/wbc-species-charts/wbc-species-linecharts/wbc-species-linecharts.component.ts
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-taxonomy/taxon-taxonomy.component.ts
- projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.ts
- projects/laji/src/app/shared-modules/collections-select/collections-select.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.ts
- projects/laji/src/app/shared-modules/document-viewer/user-document-tools/user-document-tools.component.ts
- projects/laji/src/app/shared-modules/info/info/info.component.ts
- projects/laji/src/app/shared-modules/observation-result/selected-field-group/selected-field-group.component.ts
- projects/laji/src/app/shared-modules/tree-select/selected-tree-nodes/selected-tree-nodes.component.ts
- projects/laji/src/app/shared-modules/tree-select/tree-select-modal/tree-select-modal.component.ts
- projects/laji/src/app/shared/gallery/service/gallery.service.ts
- projects/laji/src/app/shared/pipe/filter-value.pipe.ts
- tsconfig.app.json
https://220304.dev.laji.fi
`strictInputAccessModifiers` came free, didn't raise any compiler issues.
> Enable 'noImplicitAny' and 'strictInputAccessModifiers` [#180206625]

- projects/bird-atlas/src/app/app.component.ts
- projects/bird-atlas/src/app/core/api.service.ts
- projects/bird-atlas/src/app/core/atlas-api.service.ts
* adjust cache timeouts
* fix technical news query (added `lang: 'fi'`)
slack thread for both: https://luomus-ict.slack.com/archives/C02L70SLK8B/p1649688129280939
> Bird atlas fixes

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/app/+observation/search-query.service.ts
- projects/laji/src/app/graph-ql/laji.graphql
- projects/laji/src/app/shared-modules/document-viewer/user-document-tools/user-document-tools.component.html
- projects/laji/src/app/shared/model/WarehouseQueryInterface.ts
Fixed this problem: https://www.pivotaltracker.com/story/show/180175905, testable at https://180175905.viranomaiset-dev.laji.fi/
> Fix annotation system on pap 180175905 vir

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/i18n/fi.json
Filter buttons under the last filter tab, task: https://www.pivotaltracker.com/story/show/182285648, branch:  https://182285648.dev.laji.fi/observation/map.
> Virva search to laji 182285648

- projects/laji/src/app/shared-modules/spreadsheet/service/mapping.service.ts
Self-explanatory really, task: https://www.pivotaltracker.com/story/show/182319608, branch: https://182319608.dev.laji.fi/vihko/tools/import.
> Trim whitespace from coordinates on import

- projects/laji/src/app/shared-modules/spreadsheet/importer/cell-value-mapping/special-friend/special-friend.component.html
- projects/laji/src/app/shared-modules/spreadsheet/importer/cell-value-mapping/special-friend/special-friend.component.ts
Added a button to excel import to mass ignore unlinked names, task: https://www.pivotaltracker.com/story/show/182219324, branch: https://182219324.dev.laji.fi/vihko/tools/import
> Add Jätä huomioimatta -button to vihko import mapping step

- projects/laji/src/app/+observation/result/observation-result.component.html
As title says, task: https://www.pivotaltracker.com/story/show/180147507, branch: https://180147507.dev.laji.fi/observation/species?target=MX.37580.
> Added individual count sum to species tab in obs search.

- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/app/shared-modules/datatable/datatable-templates/datatable-templates.component.html
"Kansalliset kokoelmat"-filter was missing a query parameter, task: https://www.pivotaltracker.com/story/show/181768674, branch: https://181768674.dev.laji.fi/observation/list.
> Observation search filter has dropped out for some reason

- projects/laji/src/app/+home/home-data.service.ts
As the title says, task: https://www.pivotaltracker.com/story/show/181883345, branch: https://181883345.dev.laji.fi/.
> Limit front page help identifyimages to certain source systems

- projects/laji/src/app/shared/model/WarehouseQueryInterface.ts
- projects/laji/src/app/shared/omni-search/omni-search.component.ts
- projects/laji/src/app/shared/panel/panel.component.ts
- projects/laji/src/app/shared/pdf-button/pdf-button.component.ts
- projects/laji/src/app/shared/pipe/abstract-label.pipe.ts
- projects/laji/src/app/shared/pipe/area-name.pipe.ts
- projects/laji/src/app/shared/pipe/checklist.pipe.ts
- projects/laji/src/app/shared/pipe/collection-name.pipe.ts
- projects/laji/src/app/shared/pipe/coordinate.pipe.ts
- projects/laji/src/app/shared/pipe/pluck.pipe.ts
- projects/laji/src/app/shared/pipe/publication.pipe.ts
- projects/laji/src/app/shared/pipe/source.pipe.ts
- projects/laji/src/app/shared/pipe/taxon-name.pipe.ts
- projects/laji/src/app/shared/pipe/truncate.pipe.ts
- projects/laji/src/app/shared/pipe/unique.pipe.ts
- projects/laji/src/app/shared/pipe/users.pipe.ts
- projects/laji/src/app/shared/pipe/values.pipe.ts
- projects/laji/src/app/shared/service/abstract-cached-http.service.ts
- projects/laji/src/app/shared/service/area.service.ts
- projects/laji/src/app/shared/service/browser.service.ts
- projects/laji/src/app/shared/service/checklist.service.ts
- projects/laji/src/app/shared/service/collection.service.ts
- projects/laji/src/app/shared/service/confirm-modal.component.ts
- projects/laji/src/app/shared/service/delete-own-document.service.ts
- projects/laji/src/app/shared/service/export.service.ts
- projects/laji/src/app/shared/service/form.service.ts
- projects/laji/src/app/shared/service/geo-convert.service.ts
- projects/laji/src/app/shared/service/taxon-autocomplete.service.ts
- projects/laji/src/app/shared/service/user.service.ts
> More more more more strict typing [#180206625]

- projects/laji/src/app/shared-modules/spreadsheet/service/mapping.service.ts
https://www.pivotaltracker.com/story/show/182713382
> Fix vihko import not parsing coordinates that contain spaces

- projects/bird-atlas/i18n/fi.json
- projects/bird-atlas/src/app/+bird-society/bird-society-info/bird-society-info.component.html
- projects/bird-atlas/src/app/+bird-society/bird-society-info/bird-society-info.component.scss
- projects/bird-atlas/src/app/+bird-society/bird-society-info/bird-society-info.component.ts
- projects/bird-atlas/src/app/+bird-society/bird-society.module.ts
- projects/bird-atlas/src/app/+grid/grid-info/grid-info.component.html
- projects/bird-atlas/src/app/+grid/grid.module.ts
- projects/bird-atlas/src/app/+species/species-info/species-info.component.html
- projects/bird-atlas/src/app/shared-modules/grid-square/grid-square-info.component.html
- projects/bird-atlas/src/app/shared-modules/grid-square/grid-square-info.component.scss
- projects/bird-atlas/src/app/shared-modules/grid-square/grid-square-info.component.ts
- projects/bird-atlas/src/app/shared-modules/grid-square/grid-square.module.ts
Completes:
https://www.pivotaltracker.com/story/show/181354194
https://www.pivotaltracker.com/story/show/181967735
https://www.pivotaltracker.com/story/show/182059618
> [ba] Multiple small grid square info tasks

- projects/laji/src/app/shared/footer/footer.component.html
- projects/laji/src/app/shared/iucn-footer/iucn-footer.component.html
- projects/vir/src/app/component/footer/footer.component.html
(not approved on pivotal yet)
https://www.pivotaltracker.com/story/show/182393018
> add csc logo to footers

- projects/laji/src/app/shared-modules/three-state-switch/three-state-switch.component.html
https://www.pivotaltracker.com/story/show/180584573
> fix both btn-default and btn-primary being present on the same element

- projects/laji/src/app/+taxonomy/taxon/info-card/shared/service/info-card-query.service.ts
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-images/taxon-images.component.ts
https://www.pivotaltracker.com/story/show/180244284
(It's a draft, because the changes haven't been approved by Mikko yet and I'm leaving for summer holidays)
> Species image gallery: confirmed observations -> expert verified

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+taxonomy/species/species-form/species-form.component.html
- projects/laji/src/app/shared-modules/search-filters/habitat-select/habitat-select.component.html
- projects/laji/src/app/shared-modules/search-filters/habitat-select/habitat-select.component.ts
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/180991017
> Add new infotexts (questionmarks) for Species & Browse observations -sections

- projects/laji/src/app/+project-form/project-form.component.html
https://www.pivotaltracker.com/story/show/180068117
> set static width to project form sidebar

- projects/laji/src/app/shared-modules/spreadsheet/excel-generator/excel-generator.component.html
https://182328170.dev.laji.fi/vihko/tools/generate Tee Pohja buttona changed to primary (blue) button.
> Set button as primary 182328170

- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-identification/identification-list/identification-list.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.html
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document/document.component.html
- projects/laji/src/app/shared-modules/document-viewer/document/document.component.ts
- projects/laji/src/app/shared/gallery/image-gallery/image-modal-overlay.component.html
- projects/laji/src/app/shared/gallery/image-gallery/image-modal-overlay.component.ts
- projects/laji/src/app/shared/gallery/image-gallery/image-modal.component.ts
https://www.pivotaltracker.com/story/show/182700426
Also refactored image overlay a bit:
- Got rid of `childComunicationService`
- Also got rid of magic empty class method `close`
- Replaced with explicit output stream for the modal show/close state
- There's a constant stream of change detection cycles (I'm not sure what causes this still, but it's not good) so I made the component OnPush to improve performance
> Image license links

- projects/laji/src/app/+observation/form/observation-form.component.ts
https://www.pivotaltracker.com/story/show/182564517
> fix person token being overwritten by mutation of input variable

- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-info/taxon-info.component.html
Remove invasive species icon and row from taxa higher than species, https://183248340.dev.laji.fi/taxon/MX.26456
> No invasive species row for higher taxa 183248340

- projects/laji/src/app/+project-form/form/named-place/np-info/np-info.component.html
- projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.html
- projects/laji/src/app/shared-modules/info/info/info.component.ts
https://www.pivotaltracker.com/story/show/183069115
Note: test that there's not info components inside buttons (if there is, this should not be merged)
> Fix multiple tooltips 183069115

- projects/exhibition-screen/src/app/core/information.service.ts
https://www.pivotaltracker.com/story/show/183125847
> exhibition screens: confusing type error fix

- projects/laji/src/app/shared-modules/legend/laji-map-visualization.ts
- projects/laji/src/app/shared-modules/observation-map/observation-map/box-cache.ts
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.scss
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-visualization.ts
* geometries are highlighted on hover
* active geometry is highlighted
> Occurrence map interactivity

- projects/laji/src/app/+map/front/front.component.ts
- projects/laji/src/app/+project-form/form/laji-form/laji-form/laji-form.component.ts
- projects/laji/src/app/+project-form/submissions/statistics/common/accepted-document-approval/accepted-document-approval.component.ts
- projects/laji/src/app/shared-modules/document-viewer/viewer-map/viewer-map.component.ts
- projects/laji/src/app/shared-modules/laji-map-noop/laji-map.component.ts
- projects/laji/src/app/shared-modules/laji-map/laji-map.component.ts
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.html
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts
- projects/laji/src/app/shared-modules/spreadsheet/importer/cell-value-mapping/special-geometry/special-geometry.component.ts
Fixes: https://www.pivotaltracker.com/story/show/184291899
Also all occurrences of laji-map "size invalidation" were removed since it was deemed redundant.
> Occurrence map changing projection shows only small portion of data

- package-lock.json
- package.json
- projects/laji/src/app/+observation/result/observation-result.component.html
- projects/laji/src/app/shared-modules/legend/legend.component.scss
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-map.component.ts
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-visualization.ts
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/184335037
https://184335037.dev.laji.fi/observation/map
* Adds observation data layer opacity controller to the observation map.
* Removes observation map legend opacity
> Observation map data opacity [#184335037]

- projects/laji/src/app/+project-form/project-form.component.html
- projects/laji/src/app/+project-form/submissions/statistics/common/accepted-document-approval/accepted-document-approval.component.html
- projects/laji/src/app/+project-form/submissions/statistics/common/accepted-document-approval/accepted-document-approval.component.ts
- projects/laji/src/app/shared-modules/laji-map/laji-map.component.ts
https://www.pivotaltracker.com/story/show/184315076
https://dev.laji.fi/project/MHL.27/submissions/JX.295185
Fixes two things for accepted document approval view:
* null pointer error in the template code when form permissions badges are rendered
* Map view initialization - not sure what had broke but I made it work
> Fix accepted doc approval map view initialization [#184315076]

- projects/laji/src/app/+observation/form/observation-form.component.ts
https://www.pivotaltracker.com/story/show/182564517
Previously when I fixed this issue I had forgotten line 604 somehow so it was reverted. Should work as expected now.
> Bookmarking bug fix #2

- projects/laji/src/app/+save-observations/save-observations.component.html
- projects/laji/src/app/+save-observations/save-observations.component.scss
- projects/laji/src/i18n/fi.json
https://184362223.dev.laji.fi/save-observations
https://www.pivotaltracker.com/n/projects/2346653/stories/184362223
Reordered the observation system links (iNaturalist > Vihko > Löydös) and added new section for the data bank description. Changed Vihko link button style to primary.
> Save observations page reorganization [#184362223]

- projects/laji/src/app/shared-modules/legend/legend.component.html
- projects/laji/src/app/shared-modules/legend/legend.component.scss
- projects/laji/src/app/shared-modules/legend/legend.component.ts
https://www.pivotaltracker.com/story/show/184369502
> Add button for minimizing the occ viz legend

- projects/laji/src/app/+haseka/tools/sheet-importer/sheet-importer.component.ts
- projects/laji/src/app/+haseka/tools/tools-routing.module.ts
- projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.ts
- projects/laji/src/app/shared-modules/spreadsheet/spreadsheet.facade.ts
https://184341344.dev.laji.fi/vihko/tools/import
https://www.pivotaltracker.com/n/projects/2346653/stories/184341344
User is notified if trying to close tab or navigate elsewhere, while importing is ongoing. Contact me on Slack if you need an Excel document for testing.
> Warning while leaving import page [#184341344]

- projects/laji/src/app/shared-modules/tree-select/tree-select-modal/tree-select-modal.component.html
- projects/laji/src/app/shared-modules/tree-select/tree-select-modal/tree-select-modal.component.scss
- projects/laji/src/app/shared-modules/tree-select/tree-selector/tree-selector.component.html
- projects/laji/src/app/shared-modules/tree-select/tree-selector/tree-selector.component.scss
- projects/laji/src/styles/laji.scss
https://183943758.dev.laji.fi/observation/list
https://www.pivotaltracker.com/story/show/183943758
Fixes problems with modals, especially with informal group and source filter modals where the "ok" button is hard to see. This PR makes the modals to adapt to screen height and´the modal body scrollable.
> Fix modal height

- projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.ts
- projects/laji/src/app/shared-modules/annotations/annotations.component.html
- projects/laji/src/app/shared-modules/annotations/annotations.component.ts
- projects/laji/src/app/shared-modules/document-viewer/annotation-data-observation/annotation-data-observation.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.html
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document-local/document-local-viewer-view/document-local-viewer-view.component.html
- projects/laji/src/app/shared-modules/document-viewer/document-local/document-local-viewer-view/document-local-viewer-view.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document/document.component.html
- projects/laji/src/app/shared-modules/document-viewer/document/document.component.ts
- projects/laji/src/app/shared-modules/document-viewer/gathering-annotation/gathering-annotation.component.html
- projects/laji/src/app/shared-modules/document-viewer/gathering-annotation/gathering-annotation.component.ts
- projects/laji/src/app/shared-modules/document-viewer/gathering/gathering.component.html
- projects/laji/src/app/shared-modules/document-viewer/gathering/gathering.component.ts
- projects/laji/src/app/shared-modules/document-viewer/service/document-permission.service.ts
- projects/laji/src/app/shared-modules/document-viewer/unit-annotation-list/unit-annotation-list.component.html
- projects/laji/src/app/shared-modules/document-viewer/unit-annotation-list/unit-annotation-list.component.ts
- projects/laji/src/app/shared-modules/document-viewer/unit/unit.component.ts
- projects/laji/src/app/shared-modules/document-viewer/user-document-tools/user-document-tools.component.html
- projects/laji/src/app/shared-modules/document-viewer/user-document-tools/user-document-tools.component.ts
https://184459097.dev.laji.fi/project/MHL.3/submissions
https://www.pivotaltracker.com/story/show/184459097
Show edit button also for project admins in the document viewer. I refactored quite a bit so that all the code related to the permissions is now in one place (`projects/laji/src/app/shared-modules/document-viewer/service/document-permission.service.ts`)
> Show edit button for admins

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/app/+observation/search-query.service.ts
- projects/laji/src/app/graph-ql/laji.graphql
- projects/laji/src/app/shared/model/WarehouseQueryInterface.ts
- projects/laji/src/i18n/fi.json
https://184582493.dev.laji.fi/observation/list?sensitive=true
https://www.pivotaltracker.com/story/show/184582493
Adds a new filter to the observation search
> Sensitive filter

- Dockerfile
- projects/laji-api-client/src/lib/models/unit.ts
- projects/laji/src/app/graph-ql/laji.graphql
- projects/laji/src/app/shared-modules/document-viewer/unit-rows/unit-rows.component.css
- projects/laji/src/app/shared-modules/document-viewer/unit-rows/unit-rows.component.html
- projects/laji/src/app/shared-modules/document-viewer/unit-rows/unit-rows.component.ts
- projects/laji/src/app/shared/model/Units.ts
- projects/laji/src/app/shared/model/WarehouseQueryInterface.ts
- projects/laji/src/i18n/en.json
- projects/laji/src/i18n/fi.json
- projects/laji/src/i18n/sv.json
The marker should always stay next to the first row of the unit. Testable at https://183999568.dev.laji.fi/view?uri=http:%2F%2Fid.luomus.fi%2FJA.1122334456
> Added a marker to denote primary specimen to document viewer.

- projects/laji/src/app/+project-form/form/named-place/np-choose/np-choose.component.html
- projects/laji/src/app/+project-form/form/named-place/np-choose/np-list/np-list.component.ts
- projects/laji/src/app/+project-form/form/named-place/np-info/np-info.component.ts
https://184683726.dev.laji.fi/project/MHL.45/form/MHL.45/places
https://www.pivotaltracker.com/story/show/184683726
Named places list and the info modal uses labels/decision to use a label pipe from the named place form & document form schemas.
> Np list/info modal use schema [#184683726]

- projects/laji/src/app/shared-modules/legend/legend.component.html
- projects/laji/src/app/shared-modules/legend/legend.component.scss
- projects/laji/src/app/shared-modules/legend/legend.component.ts
https://www.pivotaltracker.com/story/show/185098241
> Change observation map legend hide btn styles and default to hidden on mobile

- projects/laji/src/app/shared-modules/annotations/annotations.component.ts
Story: https://www.pivotaltracker.com/story/show/184948353, testable here https://184948353.dev.laji.fi/observation/list?effectiveTag=EXPERT_TAG_ERRONEOUS&qualityIssues=ONLY_ISSUES, problem was a timer which was not unsubscribed when modal closes.
> Opening up viewer after making annotation 184948353

- projects/laji/src/app/shared-modules/annotations/annotation-form-new/annotation-form-new.component.ts
- projects/laji/src/environments/global.ts
https://www.pivotaltracker.com/story/show/185230510
> fix breeding index annotation bug

- projects/laji-ui/src/lib/sidebar/sidebar.component.ts
https://www.pivotaltracker.com/story/show/178601598
> Polygon search on firefox android fix

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/183138463
> add bird society filter

- projects/laji/src/app/+project-form/form/named-place/np-print/line-transect-print/line-transect-print.component.html
- projects/laji/src/app/+project-form/form/named-place/np-print/line-transect-print/line-transect-print.component.ts
https://185286435.dev.laji.fi/project/MHL.1/form/MHL.1/places
https://www.pivotaltracker.com/story/show/185286435
> Line transect pdf fixes

- projects/laji/src/app/+project-form/form/named-place/np-print/line-transect-print/line-transect-print.component.scss
https://185286435.dev.laji.fi/project/MHL.1/form/MHL.1/places/MNP.27169/print
Line transect pdf was missing pages when the map page is in the landscape mode
> Fix line transect pdf

- projects/bird-atlas/src/index.html
- projects/iucn/src/index.html
- projects/kerttu-global/src/index.html
- projects/laji/src/index.html
This pull request replaces all the google analytics tags with plausible.
> Add plausible tags

- projects/laji/src/app/shared/datepicker/datepicker.component.html
- projects/laji/src/app/shared/datepicker/datepicker.component.ts
Task here https://www.pivotaltracker.com/story/show/184710661, also added the handler for keypress' to catch enter-keys to set the value.
> Selecting year range as time #184710661

- projects/laji/src/app/shared-modules/spreadsheet/service/spreadsheet.service.ts
Task here https://www.pivotaltracker.com/story/show/184222093, not much to say, just made sure both sides of comparisons are in lowercase.
> Ignoe case of coordinate system in excel import #184222093

- projects/laji/src/app/+project-form/results/common/theme-observation-list/theme-observation-list.component.ts
Task here https://www.pivotaltracker.com/story/show/185049549, new column to nafi tables.
> Add common name to NAFI result service #185049549

- projects/laji/src/app/shared-modules/datatable/datatable/datatable.component.ts
Task here https://www.pivotaltracker.com/story/show/180887524, wrote logic to put sorting changes reversed into the sorting array.
> Column sorting usability 180887524

- projects/laji/src/app/shared/feedback/feedback.component.ts
Task here https://www.pivotaltracker.com/story/show/184670721, problem is that in red book there is no user, and RXJS does not execute observables and pipes if that observable is an empty value, like in userless case here, so now feedback form has an check based on presence of user persontoken to chose how it does the feedback sending.
> Punainenkirja feedback form broken #184670721

- projects/laji/src/app/shared/footer/footer.component.html
Task here https://www.pivotaltracker.com/story/show/184591629, just updated links to point to new images in CMS.
> Update some logos in footer #184591629

- projects/laji/src/app/+observation/form-sample/form-sample.component.html
- projects/laji/src/app/+observation/form/date-form/date-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/observation.module.ts
- projects/laji/src/app/shared/directive/disable-wheel.directive.ts
- projects/laji/src/app/shared/shared.module.ts
Task here https://www.pivotaltracker.com/story/show/185645030, added a directive that can be added to fields to disable scroll events.
> Disable scrolling on observation search numeric fields #185645030

- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/+observation/form/observation-form.component.ts
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/182740201
> Add bird atlas filter shortcut

- projects/laji/src/app/+observation/result/observation-result.component.html
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-occurrence/taxon-occurrence.component.html
- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.component.html
- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.component.ts
- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.facade.ts
https://www.pivotaltracker.com/story/show/184106670
https://184106670.dev.laji.fi/
> Month day chart bugfix & refactor

- projects/laji/src/app/+observation/download/observation-download.component.ts
- projects/laji/src/app/+observation/observation-data.service.ts
- projects/laji/src/app/+observation/observation.facade.ts
- projects/laji/src/app/+observation/search-query.service.ts
Task here https://www.pivotaltracker.com/story/show/184872045.
> Habitat filter or is broken 184872045

- projects/laji/src/app/+project-form/about/about.component.html
- projects/laji/src/app/+project-form/project-form.component.html
- projects/laji/src/app/+project-form/project-form.component.ts
- projects/laji/src/app/shared-modules/latest-documents/latest-documents.facade.ts
- projects/laji/src/app/shared-modules/latest-documents/latest/haseka-users-latest.component.ts
Task here https://www.pivotaltracker.com/story/show/184962458
> Imported observations dont show under newest observations 184962458

- projects/laji/src/app/+project-form/form/named-place/named-place/named-place.component.ts
Task here https://www.pivotaltracker.com/story/show/182152439
> Line transect page makes duplicate requests 182152439

- projects/laji/src/app/shared-modules/spreadsheet/importer/cell-value-mapping/cell-value-mapping.component.ts
- projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.ts
- projects/laji/src/app/shared-modules/spreadsheet/service/mapping.service.ts
Task https://www.pivotaltracker.com/story/show/184272933, testable here https://184272933.dev.laji.fi/.
> Allow mapping to empty value 184272933

- projects/kerttu-global/src/app/+identification/identification-history/identification-history-edit-modal/identification-history-edit-modal.component.ts
- projects/kerttu-global/src/app/+identification/identification-history/identification-history.component.ts
- projects/laji-ui/src/lib/_vars.scss
- projects/laji-ui/src/lib/modal/modal.service.ts
- projects/laji-ui/src/lib/modal/modal/modal.component.scss
- projects/laji-ui/src/lib/modal/modal/modal.component.ts
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.scss
- projects/laji/src/app/shared-modules/tree-select/tree-select-modal/tree-select-modal.component.ts
- projects/laji/src/app/shared-modules/tree-select/tree-select.component.ts
Check the commit messages for description for what is fixed (click them open, they are multi line messages)
> Modal fixes

- projects/laji/src/app/shared-modules/model-viewer/webgl/mini-renderer.ts
- projects/laji/src/app/shared-modules/model-viewer/webgl/webgl-utils.ts
https://luomus-ict.slack.com/archives/CQEQSQCP7/p1700214321673549
> Fix webgl memory leak

- projects/laji-ui/src/lib/popover/popover-container.component.scss
- projects/laji-ui/src/lib/popover/popover-container.component.ts
- projects/laji-ui/src/lib/popover/popover.directive.ts
- projects/laji/src/app/+observation/form/observation-form.component.html
- projects/laji/src/app/shared-modules/observation-map/observation-map/observation-visualization.ts
```
obs map vis beta test bug
popover close button
vakioidut rajaukset to PAP
```
> Beta fixes

- projects/laji/src/app/+taxonomy/taxon/taxon-tree/taxon-tree.component.html
- projects/laji/src/app/+taxonomy/taxon/taxon-tree/tree/tree.component.ts
https://github.com/luomus/laji/pull/467#discussion_r1410585696
> Don't pass a ng-template inside content projection

- .gitignore
- README.md
- package-lock.json
- package.json
- playwright.config.ts
- projects/laji/test/+user/user.spec.ts
I didn't migrate `user.po.ts`. Stuff in there should be implemented when/if they are needed.
> Migrate user e2e tests

- projects/laji/src/app/+observation/form/conservation-filter/conservation-filter.component.html
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.html
- projects/laji/src/app/shared-modules/select/metadata-select/metadata-select.component.ts
- projects/laji/src/app/shared-modules/select/select/select.component.html
- projects/laji/src/app/shared-modules/select/select/select.component.ts
- projects/laji/src/app/shared/pipe/filter.pipe.ts
- projects/laji/src/app/shared/service/filter.service.ts
https://www.pivotaltracker.com/story/show/186331507
With some added type magic on the side...
> Make filters only use titles in selected language

- projects/laji/src/app/shared-modules/spreadsheet/importer/importer.component.html
https://186579280.dev.laji.fi/vihko/tools/import
https://www.pivotaltracker.com/n/projects/2346653/stories/186579280
Removed the excel intro text from importer.
> Remove excel intro text from importer [#186579280]

- projects/laji/src/app/shared-modules/document-viewer/identifications/identification/identification.component.html
- projects/laji/src/app/shared-modules/document-viewer/types/type/type.component.html
Task here https://www.pivotaltracker.com/story/show/186597476, testable here https://186597476.dev.laji.fi/
> Identification section change for taxon specifier 186597476

- projects/laji/src/app/shared/navbar/navbar.component.html
- projects/laji/src/app/shared/navbar/navbar.component.scss
Task here https://www.pivotaltracker.com/story/show/186579353, testable here https://186579353.dev.laji.fi/
> Lajit not visible on mobile menu 186579353

- projects/laji-ui/src/lib/sidebar/sidebar.component.html
- projects/laji-ui/src/lib/sidebar/sidebar.component.scss
Task here https://www.pivotaltracker.com/story/show/186579345, testable here https://186579345.dev.laji.fi/
> Taxonomy sidebar cannot be closed on mobile 186579345

- projects/laji/src/app/shared/navbar/navbar.component.ts
Task here https://www.pivotaltracker.com/story/show/186579386, testable here https://186579386.dev.laji.fi/
> Close mobile navbar dropdown on clicking outside of it 186579386

- projects/laji/src/app/shared/navbar/navbar.component.html
- projects/laji/src/app/shared/navbar/navbar.component.scss
- projects/laji/src/app/shared/navbar/navbar.component.ts
Task here https://www.pivotaltracker.com/story/show/186579364, testable here https://186579364.dev.laji.fi/
> Language selection layout is broken 186579364

- projects/iucn/src/app/+about/about.component.ts
- projects/laji/src/app/shared-modules/info-page/info-page.component.ts
https://www.pivotaltracker.com/story/show/186361891
https://punainenkirja-dev.laji.fi/about/r-25
> iucn: Exclude some pages from breadcrumb hierarchy

- projects/laji/src/app/shared-modules/document-viewer/document/document.component.html
- projects/laji/src/i18n/fi.json
https://www.pivotaltracker.com/story/show/186844044
https://186844044.dev.laji.fi/
> Add clarifying text for docs where sensitive observations were removed

- projects/laji/src/app/+news/news.component.html
- projects/laji/src/app/+news/news.component.scss
- projects/laji/src/app/+news/news.component.ts
- projects/laji/src/app/shared/model/News.ts
https://www.pivotaltracker.com/story/show/182556068
https://182556068.dev.laji.fi/news/i-7674
> Add featured images to news

- projects/laji/src/app/+taxonomy/taxon/taxon.component.ts
https://www.pivotaltracker.com/story/show/186579262
https://186579262.dev.laji.fi/taxon/MX.50934850937845
> Display taxon not found message

- projects/laji-ui/src/lib/placement/placement.service.ts
- projects/laji-ui/src/lib/popover/popover.directive.ts
- projects/laji-ui/src/lib/tooltip/tooltip.directive.ts
- projects/laji/src/app/shared-modules/info/info/info.component.ts
https://www.pivotaltracker.com/story/show/186971282
> Automatically place popovers such that they fit the screen

- projects/kerttu-global/src/app/+identification/recording-identification/identification-view/identification-table/identification-panel/identification-panel.component.html
- projects/laji-ui/src/lib/alert/alert.component.ts
- projects/laji-ui/src/lib/popover/popover-container.component.ts
- projects/laji/src/app/+observation/main-result/main-result.component.html
- projects/laji/src/app/+project-form/results/common/theme-observation-list/theme-observation-list.component.html
- projects/laji/src/app/shared-modules/document-viewer/document-annotation/document-annotation.component.html
- projects/laji/src/app/shared/datepicker/datepicker.component.html
Replaces all '>x<' with '>✕<'. Looks better.
> Replace x with ✕ for as close glyph

- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.component.ts
Task: https://www.pivotaltracker.com/story/show/187304273, testable here: https://187304273.dev.laji.fi/observation/statistics?target=MX.37580&time=2023-01-01%2F2023-12-31
> Erroneous days on monthly charts #187304273

- projects/laji/src/app/+project-form/results/biomon-result/biomon-result.component.ts
- projects/laji/src/app/+project-form/results/bird-point-count-result/bird-point-count-result.component.ts
https://187592034.dev.laji.fi/project/MHL.932/stats?tab=map
https://www.pivotaltracker.com/n/projects/2346653/stories/187592034
Fixed bug where the taxon dropdown resets to "All taxa" after changing value.
> Fix Biomon result service dropdown [#187592034]

- projects/laji/src/app/shared-modules/observation-result/observation-year-chart/observation-year-chart.component.ts
https://www.pivotaltracker.com/story/show/187698327
https://187698327.dev.laji.fi/observation/statistics
> Fix observation year chart toggle button not working

- projects/laji/src/app/shared/service/collection.service.ts
https://187698576.dev.laji.fi/observation/list
https://www.pivotaltracker.com/n/projects/2346653/stories/187698576
Fixed the observation sources query by adding the actual observerPersonToken instead of "true".
> Fixed observation sources query [#187698576]

- projects/laji-ui/src/lib/sidebar/sidebar.component.html
- projects/laji/src/app/+information/information.component.css
- projects/laji/src/app/+information/information.component.html
https://www.pivotaltracker.com/story/show/187765471
https://187765471.dev.laji.fi/about/5719
> improve about pages on mobile

- package-lock.json
- package.json
- projects/laji/src/app/shared/api/FormApiClient.ts
https://www.pivotaltracker.com/story/show/187377607
Adds support for adding large FLAC audio files to Vihko
> Flac audio

- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.component.ts
- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.facade.ts
https://www.pivotaltracker.com/story/show/188126950
https://188126950.dev.laji.fi/observation/statistics
> Fix days missing from the day chart

- projects/laji/src/app/shared-modules/observation-result/observation-month-day-chart/observation-month-day-chart.facade.ts
https://www.pivotaltracker.com/story/show/188127003
https://188127003.dev.laji.fi/observation/statistics
> Fix day chart shows life stage wrong

- projects/laji/src/app/shared/service/user.service.ts
Fixes https://luomus-ict.slack.com/archives/CQEQSQCP7/p1724406648826119
Also gave the ready user state a more descriptive tag
https://762038495.dev.laji.fi/
> Validate user service local storage state

- projects/laji/src/app/shared/service/user.service.ts
Two issues:
- user service `user$` behavior didn't exactly correspond to old one after refactor. It used to return `Person | undefined` and now it was returning just `Person`
- there was a bug in that the person part was in loading state instead of logged out state
https://42398123.dev.laji.fi/
> user$ should return undefined when user is not logged in

- projects/laji-ui/src/lib/placement/placement.service.ts
- projects/laji-ui/src/lib/typeahead/positioning/positioning.service.ts
- projects/laji-ui/src/lib/typeahead/typeahead-container.component.ts
- projects/laji/src/styles/laji.scss
https://www.pivotaltracker.com/story/show/188206822
https://188206822.dev.laji.fi/observation
> Autocomplete opens on top of input

- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-info/taxon-info.component.html
- projects/laji/src/app/+taxonomy/taxon/info-card/taxon-overview/taxon-info/taxon-info.component.ts
- projects/laji/src/app/shared/model/Taxonomy.ts
- projects/laji/src/i18n/fi.json
https://188250427.dev.laji.fi/taxon/MX.37641
https://www.pivotaltracker.com/story/show/188250427
Adds a protected status to the taxon card if the species is protected under nature conservation act.
> Protected status

- projects/laji/src/app/shared-modules/latest-documents/latest/short-document.component.html
https://www.pivotaltracker.com/story/show/187481882
https://187481882.dev.laji.fi/vihko/home
> Removed unnecesssary tooltips from recent submission buttons  #187481882

- package-lock.json
- package.json
- playwright.config.ts
- projects/laji/src/app/shared-modules/search-filters/active/observation-active.component.html
- projects/laji/src/app/shared-modules/search-filters/active/observation-active.component.ts
- projects/laji/src/app/shared/datepicker/datepicker.component.html
- projects/laji/src/app/shared/datepicker/datepicker.component.ts
- projects/laji/test/+observation/observation.spec.ts
- projects/laji/test/+project-form/project-form.spec.ts
- projects/laji/test/+theme/datasets/datasets.spec.ts
- projects/laji/test/+user/user.po.ts
- projects/laji/test/+vihko/tools.spec.ts
- projects/laji/test/+vihko/trip-form.spec.ts
- projects/laji/test/shared/toast.ts
- test.Dockerfile
Fixes many flaky tests and skips those that seemed difficult to fix
> Playwright fixes

- projects/laji/src/app/shared/service/form-permission.service.ts
Fixes bug with https://github.com/luomus/laji/pull/574 (http://localhost:3000/project/JX.519/form throws collectionID is undefiend)
> Fix form perms undefined

- .github/workflows/lint.yml
- package.json
Testing github actions linting...
> Disable pre push hook

- projects/laji-api-client/src/lib/laji-api-client.service.ts
- projects/laji-api-client/src/lib/models/profile.ts
- projects/laji/src/app/+user/friends/friends.component.html
- projects/laji/src/app/+user/friends/friends.component.ts
- projects/laji/src/app/+user/profile/profile.component.html
- projects/laji/src/app/graph-ql/laji.graphql
- projects/laji/src/app/shared/api/PersonApi.ts
- projects/laji/src/app/shared/model/Profile.ts
* Make friend request based on personID instead of profile key
* Refactor PersonApi: remove useless type checks and query param manipulation
Closes #670
> Make friend requests based on person id

- projects/laji/src/app/+theme/identify/identify.component.html
Removed the "which species -form" button, and applied innerHTML for the translations so links can be added.
Closes #598
> Removed which species -form button

- projects/laji/src/app/+home/home-data.service.ts
- projects/laji/src/app/+home/home.component.html
- projects/laji/src/app/+home/home.component.scss
- projects/laji/src/styles/laji.scss
- projects/vir/src/app/+home/home.component.html
- projects/vir/src/app/+home/home.component.scss
Adds news section to PAP. Shows news with a tag "viranomaiset" only in PAP.  [closes #662]
> News to Public Authority Portal
